Repository ita-social-projects/horondi_client_be, pull requests merged in 2020-08, with the labels that each got.

#119 Removed video & added show in news model
  modules/news/news.graphql.js
  modules/news/news.model.js
Labels: change request, data base

#120 Added model for contacts collection
  models/Contact.js
Labels: Task, data base

#117 Unregistered users can leave comments; registered users can change their rating
  modules/comment/comment.graphql.js
  modules/comment/comment.model.js
  modules/product/product.graphql.js
  modules/product/product.model.js
  modules/user/user.graphql.js
  typeDefs.js
Labels: change request, data base

#109 Test v3
  __tests__/news/__snapshots__/news.query.test.js.snap
  __tests__/news/news.mutation.test.js
  __tests__/news/news.query.test.js
  __tests__/user/__snapshots__/user.query.test.js.snap
  codegen.yml
  config/db.js
  fragmentTypes.json
  jest.config.js
  models/Contact.js
  modules/category/category.resolver.js
  modules/category/category.service.js
  modules/comment/comment.model.js
  modules/currency/currency.resolver.js
  modules/currency/currency.service.js
  modules/material/material.resolver.js
  modules/material/material.service.js
  modules/news/news.resolver.js
  modules/news/news.service.js
  modules/pattern/pattern.resolver.js
  modules/pattern/pattern.service.js
  modules/product/product.model.js
  modules/product/product.resolver.js
  package-lock.json
  package.json
  typeDefs.js
  utils/apollo-test-client.js
Labels: test

#122 Db product models (for slider)
  models/Model.js
Labels: Task, data base

#141 Modified address in contacts
  models/Contact.js
Labels: change request, data base

#140 Db prices for 2 currencies
  models/Closure.js
  models/CurrencySet.js
  models/Size.js
  modules/material/material.graphql.js
  modules/material/material.model.js
  modules/product/product.graphql.js
  modules/product/product.model.js
  typeDefs.js
Labels: change request, data base

#142 Added fields to address, news, material models; modified orders model
  models/Order.js
  modules/common/Address.js
  modules/material/material.graphql.js
  modules/material/material.model.js
  modules/news/news.graphql.js
  modules/news/news.model.js
  modules/user/user.model.js
  typeDefs.js
Labels: change request, data base

#137 Comments fix
  error-messages/comment.messages.js
  modules/comment/comment.resolver.js
  modules/comment/comment.service.js
  resolvers.js
  typeDefs.js
Labels: refactoring

#143 Contacts
  __tests__/news/__snapshots__/news.query.test.js.snap
  __tests__/news/news.query.test.js
  __tests__/user/user.mutation.test.js
  error-messages/contact.messages.js
  modules/contact/contact.graphql.js
  modules/contact/contact.model.js
  modules/contact/contact.resolver.js
  modules/contact/contact.service.js
  modules/product/product.resolver.js
  modules/product/product.service.js
  modules/user/user.service.js
  resolvers.js
  typeDefs.js
Labels: Task

#134 Upload photos
  modules/comment/common/Address.js
  modules/comment/common/ImageSet.js
  modules/upload/upload.resolver.js
  modules/upload/upload.service.js
  package.json
  resolvers.js
  typeDefs.js
Labels: Task
