Repository ita-social-projects/horondi_client_be, pull requests merged in 2020-10, with the labels that each got.

#203 Contacts upload
  modules/contact/contact.graphql.js
  modules/contact/contact.permission.js
  modules/contact/contact.resolver.js
  modules/contact/contact.service.js
  modules/upload/upload.service.js
  permissions.js
  typeDefs.js
Labels: Task

#233 Fixed superadmin deleting bug
  error-messages/user.messages.js
  modules/user/user.model.js
  modules/user/user.resolver.js
  typeDefs.js
Labels: enhancement

#252 User`s orders query
  .env.test
  __tests__/user/user.variables.js
  modules/order/order.resolver.js
  modules/order/order.service.js
  typeDefs.js
Labels: Task

#239 Refactor order and pattern tests approach
  __tests__/order/order.mutation.test.js
  __tests__/order/order.query.test.js
  __tests__/order/order.variables.js
  __tests__/pattern/__snapshots__/pattern.query.test.js.snap
  __tests__/pattern/pattern.mutation.test.js
  __tests__/pattern/pattern.query.test.js
  __tests__/pattern/pattern.variables.js
  app.js
Labels: Task, test

#256 Email questions v2
  error-messages/header.messages.js
  modules/email-chat/email-chat.model.js
  modules/email-chat/email-chat.resolver.js
  modules/email-chat/email-chat.service.js
  modules/email-chat/email-question.graphql.js
  modules/header/header.service.js
  package.json
  typeDefs.js
  utils/getTime.js
  utils/localization.js
Labels: Task

#249 Module service
  modules/modules.service.js
Labels: Task

#212 Business pages images settings
  .eslintrc
  error-messages/business-text.messages.js
  error-messages/model.messages.js
  modules/business-text/business-text.resolver.js
  modules/business-text/business-text.service.js
  modules/model/model.resolver.js
  modules/model/model.service.js
  typeDefs.js
Labels: Task

#259 User statistic
  consts/index.js
  modules/helper-functions.js
  modules/user/user.graphql.js
  modules/user/user.permissions.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  typeDefs.js
Labels: Task

#268 fix bug
  modules/user/user.service.js
Labels: bug

#274 Fix of security leak when user could change his/her role
  modules/user/user.graphql.js
  modules/user/user.service.js
  server.js
  typeDefs.js
Labels: Task

#270 Total stats
  modules/order/order.service.js
  modules/product/product.service.js
  modules/user/user.service.js
  typeDefs.js
Labels: Task

#277 Material upload colors
  error-messages/material.messages.js
  modules/material/material.resolver.js
  modules/material/material.service.js
  resolvers.js
  typeDefs.js
Labels: Task

#275 Getting data for burger menu
  modules/category/category.resolver.js
  modules/category/category.service.js
  typeDefs.js
Labels: Task

#266 Homepage edit
  __tests__/model/model.mutation.test.js
  error-messages/home-page-messages.js
  modules/homepage-images/home-page-images.graphql.js
  modules/homepage-images/home-page-images.model.js
  modules/homepage-images/home-page-images.permissions.js
  modules/homepage-images/home-page-images.resolver.js
  modules/homepage-images/home-page-images.service.js
  permissions.js
  resolvers.js
  typeDefs.js
Labels: Task

#278 Order page
  modules/order/order.graphql.js
  modules/order/order.model.js
  modules/order/order.service.js
  typeDefs.js
Labels: Task

#273 User filters
  consts/index.js
  modules/user/user.graphql.js
  modules/user/user.service.js
  typeDefs.js
Labels: Task

#280 User filters hotfix
  modules/user/user.service.js
Labels: Task
