Repository ita-social-projects/horondi_client_be, pull requests merged in 2020-09, with the labels that each got.

#154 Added user restrictions by roles
  __tests__/user/user.mutation.test.js
  __tests__/user/user.query.test.js
  modules/upload/upload.service.js
  modules/user/user.permissions.js
  package-lock.json
  package.json
  permissions.js
  server.js
  typeDefs.js
  utils/rules.js
Labels: Task

#188 Modified Orders model
  models/Order.js
Labels: change request, data base

#172 Add user admin
  __tests__/contact/contact.mutation.test.js
  __tests__/contact/contact.query.test.js
  __tests__/helpers/admin-login.js
  __tests__/product/__snapshots__/product.query.test.js.snap
  __tests__/product/product.mutation.test.js
  __tests__/user/user.mutation.test.js
  __tests__/user/user.query.test.js
  __tests__/user/user.variables.js
  consts/index.js
  error-messages/user.messages.js
  errors/rule.error.js
  models/Order.js
  modules/comment/comment.resolver.js
  modules/comment/comment.service.js
  modules/contact/contact.resolver.js
  modules/model/model.resolver.js
  modules/product/product.service.js
  modules/upload/upload.service.js
  modules/user/user.graphql.js
  modules/user/user.permissions.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  package-lock.json
  permissions.js
  plugins/error-output.plugin.js
  resolvers.js
  server.js
  typeDefs.js
  utils/format-error.js
  utils/localization.js
  utils/rules.js
  utils/validate-user.js
Labels: Task

#201 Material permissions hotfix
  modules/material/material.permissions.js
Labels: bug

#180 Business pages
  __tests__/business-text/business-text.mutation.test.js
  __tests__/business-text/business-text.query.test.js
  __tests__/business-text/business-text.variables.js
  __tests__/helpers/admin-login.js
  __tests__/user/user.query.test.js
  __tests__/user/user.variables.js
  consts/index.js
  error-messages/business-text.messages.js
  error-messages/user.messages.js
  errors/rule.error.js
  modules/business-text/business-text.graphql.js
  modules/business-text/business-text.model.js
  modules/business-text/business-text.resolver.js
  modules/business-text/business-text.service.js
  modules/product/product.resolver.js
  modules/user/user.permissions.js
  modules/user/user.resolver.js
  resolvers.js
  typeDefs.js
  utils/localization.js
  utils/rules.js
  utils/validate-user.js
Labels: Task

#210 User filters
  __tests__/user/user.mutation.test.js
  modules/user/user.graphql.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  typeDefs.js
Labels: Task

#186 User comments
  __tests__/comment/comment.query.test.js
  __tests__/comment/comment.variables.js
  __tests__/contact/contact.mutation.test.js
  __tests__/contact/contact.query.test.js
  modules/comment/comment.resolver.js
  modules/comment/comment.service.js
  typeDefs.js
Labels: Subtask

#216 Fixed an issue with plugin
  plugins/error-output.plugin.js
Labels: bug

#218 Test restrictions
  permissions.js
  plugins/error-output.plugin.js
Labels: bug
