Repository ita-social-projects/horondi_client_be, pull requests merged in 2020-11, with the labels that each got.

#285 User cart & wishlist
  modules/product/product.graphql.js
  modules/product/product.service.js
  modules/user/user.graphql.js
  modules/user/user.model.js
  modules/user/user.permissions.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  package-lock.json
  package.json
  typeDefs.js
Labels: Task

#294 business pages hot fix
  modules/business-text/business-text.resolver.js
  modules/business-text/business-text.service.js
  package-lock.json
  utils/token.js
Labels: bug

#304 Homepage edit test
  .env.test~7617950a8469fe7ca963c767450e2359352e805b
  __tests__/contact/__snapshots__/contact.query.test.js.snap
  __tests__/homepage-images/homepage-images.mutation.test.js
  __tests__/homepage-images/homepage-images.query.test.js
  __tests__/homepage-images/homepage-images.variables.js
  __tests__/materials/__snapshots__/material.query.test.js.snap
  __tests__/materials/material.query.test.js
  __tests__/pattern/__snapshots__/pattern.query.test.js.snap
  modules/email-chat/email-chat.resolver.js
  modules/homepage-images/home-page-images.permissions.js
  modules/homepage-images/home-page-images.resolver.js
  modules/homepage-images/home-page-images.service.js
  resolvers.js
  typeDefs.js
Labels: test

#302 Home page slider model
  .env.test~7617950a8469fe7ca963c767450e2359352e805b
  error-messages/home-page-slider.messages.js
  modules/homepage-slider/homepage-slider.graphql.js
  modules/homepage-slider/homepage-slider.model.js
  modules/homepage-slider/homepage-slider.resolves.js
  modules/homepage-slider/homepage-slider.service.js
  resolvers.js
  typeDefs.js
Labels: Task

#297 fix process enviroment variables
  __tests__/helper-functions.js
  __tests__/materials/material.variables.js
  __tests__/news/news.variables.js
  __tests__/pattern/pattern.query.test.js
  __tests__/pattern/pattern.variables.js
  __tests__/user/user.mutation.test.js
  __tests__/user/user.query.test.js
  __tests__/user/user.variables.js
  app.js
  config/db.js
  currency.worker.js
  dotenvValidator.js
  logger.js
  modules/business-text/business-text.service.js
  modules/confirm-email/confirmation-email.service.js
  modules/delivery/delivery.service.js
  modules/email-chat/email-chat.service.js
  modules/payment/payment.service.js
  modules/upload/upload.service.js
  modules/user/user.service.js
  package.json
  server.js
  utils/apollo-test-client.js
  utils/configService.js
  utils/create-token.js
  utils/localization.js
  utils/sendGrid-email.js
  utils/sendmail.js
  utils/token.js
  utils/verify-user.js
Labels: bug

#308 delete .env trest
  .env.test~7617950a8469fe7ca963c767450e2359352e805b
Labels: bug

#311 Fix of categories deleting tests
  __tests__/model/model.mutation.test.js
  __tests__/model/model.query.test.js
  __tests__/product/product.variables.js
Labels: refactoring

#300 Logger
  dotenvValidator.js
  logger.js
  loggerHttp.js
  modules/order/order.service.js
  modules/user/user.service.js
  server.js
Labels: Task

#309 Implemented test for Users
  __tests__/helper-functions.js
  __tests__/helpers/users.js
  __tests__/user/user.query.test.js
  __tests__/user/user.variables.js
Labels: test

#324 Fix tests
  __tests__/helpers/users.js
  __tests__/user/user.mutation.test.js
  __tests__/user/user.query.test.js
  __tests__/user/user.variables.js
  package-lock.json
Labels: test

#318 Subcategories delete from products
  __tests__/product/product.mutation.test.js
  __tests__/product/product.query.test.js
  __tests__/product/product.variables.js
  modules/category/category.service.js
  modules/product/product.graphql.js
  modules/product/product.model.js
  resolvers.js
Labels: special task

#325 Fix tests
  .gitignore
  __tests__/teardown.js
  jest.config.js
  package.json
  sonar-project.properties
Labels: test
