Repository ita-social-projects/horondi_client_be, pull requests merged in 2020-12, with the labels that each got.

#329 Added refresh token management
  dotenvValidator.js
  error-messages/user.messages.js
  modules/user/user.graphql.js
  modules/user/user.permissions.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  resolvers.js
  typeDefs.js
  utils/create-token.js
  utils/token.js
Labels: Task

#342 Payment service
  modules/payment/payment.graphql.js
  modules/payment/payment.resolver.js
  modules/payment/payment.service.js
  typeDefs.js
Labels: Subtask

#382 Refactor upload
  consts/index.js
  modules/business-text/business-text.service.js
  modules/category/category.service.js
  modules/comment/comment.service.js
  modules/contact/contact.service.js
  modules/contact/contact.utils.js
  modules/homepage-images/home-page-images.service.js
  modules/homepage-slider/homepage-slider.service.js
  modules/material/material.service.js
  modules/model/model.service.js
  modules/pattern/pattern.service.js
  modules/product/product.service.js
  modules/product/product.utils.js
  modules/upload/upload.service.js
Labels: refactoring

#381 News database fix
  modules/news/news.graphql.js
  modules/news/news.model.js
  typeDefs.js
Labels: DB

#375 Refactor color schema
  error-messages/color.massage.js
  error-messages/size.messages.js
  error-messages/sizes.messages.js
  modules/color/color.graphql.js
  modules/color/color.model.js
  modules/color/color.permissions.js
  modules/color/color.resolver.js
  modules/color/color.service.js
  modules/material/material.graphql.js
  modules/material/material.model.js
  modules/material/material.resolver.js
  modules/material/material.service.js
  modules/product/product.graphql.js
  modules/product/product.model.js
  modules/size/size.graphql.js
  modules/size/size.permissions.js
  modules/size/size.resolver.js
  modules/size/size.service.js
  permissions.js
  resolvers.js
  typeDefs.js
Labels: DB, refactoring

#380 Refactor user model
  modules/order/order.model.js
  modules/product/product.graphql.js
  modules/user/user.graphql.js
  modules/user/user.model.js
  modules/user/user.permissions.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  tests/user/user.mutation.test.js
  tests/user/user.query.test.js
  typeDefs.js
Labels: DB

#387 News fix
  error-messages/news.messages.js
  modules/news/news.graphql.js
  modules/news/news.resolver.js
  modules/news/news.service.js
  modules/upload/upload.service.js
  modules/upload/upload.utils.js
  typeDefs.js
Labels: DB

#388 add-closures
  error-messages/closures.messages.js
  modules/closures/closures.graphql.js
  modules/closures/closures.model.js
  modules/closures/closures.permission.js
  modules/closures/closures.resolver.js
  modules/closures/closures.service.js
  permissions.js
  resolvers.js
  typeDefs.js
Labels: Task
