Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-01, with the labels that each got.

#395 Fix patterns schema
  modules/color/color.service.js
  modules/pattern/pattern.graphql.js
  modules/pattern/pattern.model.js
  server.js
Labels: refactoring

#398 refactor news upload
  modules/news/news.model.js
  modules/news/news.resolver.js
  modules/news/news.service.js
Labels: refactoring

#376 Refactor products model
  .env.example
  .env.test.example
  .github/workflows/main.yml
  dotenvValidator.js
  modules/product/product.graphql.js
  modules/product/product.model.js
  modules/product/product.service.js
  modules/product/product.utils.js
  typeDefs.js
  utils/configService.js
Labels: BackEnd

#405 add multiple color adding to material
  modules/color/color.service.js
  modules/material/material.graphql.js
  modules/material/material.model.js
  modules/material/material.service.js
Labels: BackEnd, DB, refactoring

#408 Constructor colors refactor
  modules/constructor/constructor-basic/constructor-basic.graphgl.js
  modules/constructor/constructor-basic/constructor-basic.model.js
  modules/constructor/constructor-bottom/constructor-bottom.graphql.js
  modules/constructor/constructor-bottom/constructor-bottom.model.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.graphgl.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.model.js
  modules/constructor/constructor.services.js
  modules/model/model.service.js
Labels: refactoring

#372 order mongoose model
  models/Delivery.js
  models/OrderItem.js
  modules/order/order.graphql.js
  modules/order/order.model.js
  modules/order/order.resolver.js
  modules/order/order.service.js
  modules/order/order.utils.js
  package-lock.json
  typeDefs.js
Labels: BackEnd, DB

#425 Fix materials tests
  modules/currency/__mocks__/currency.utils.js
  modules/material/material.service.js
  tests/materials/__snapshots__/material.query.test.js.snap
  tests/materials/material.mutation.test.js
  tests/materials/material.query.test.js
  tests/materials/material.variables.js
Labels: BackEnd, DB, test

#429 product model fix
  modules/product/product.graphql.js
  modules/product/product.model.js
  modules/product/product.service.js
  modules/product/product.utils.js
  resolvers.js
  typeDefs.js
Labels: BackEnd, DB, refactoring

#431 fix product graphql
  modules/constructor/constructor-basic/constructor-basic.model.js
  modules/constructor/constructor-bottom/constructor-bottom.graphql.js
  modules/constructor/constructor-bottom/constructor-bottom.model.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.model.js
  modules/constructor/constructor.services.js
  modules/model/model.service.js
  modules/product/product.graphql.js
  typeDefs.js
Labels: DB

#433 Fixed order model
  modules/order/order.graphql.js
  modules/order/order.service.js
  modules/order/order.utils.js
  resolvers.js
Labels: BackEnd, DB, refactoring

#434 make audit fix dry run
  package-lock.json
  package.json
Labels: bug, priority high

#424 Add sizes to models
  error-messages/constructor-basic-messages.js
  error-messages/constructor-front-pocket-messages.js
  modules/constructor/constructor-basic/constructor-basic.permission.js
  modules/constructor/constructor-basic/constructor-basic.resolves.js
  modules/constructor/constructor-bottom/constructor-bottom.resolver.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.permission.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.resolves.js
  modules/constructor/constructor.services.js
  modules/currency/currency.utils.js
  modules/model/model.graphql.js
  modules/model/model.model.js
  modules/model/model.resolver.js
  modules/size/size.graphql.js
  modules/size/size.resolver.js
  modules/size/size.service.js
  permissions.js
  resolvers.js
  typeDefs.js
Labels: BackEnd, DB, refactoring

#436 constructor-Basics-tests #423
  modules/constructor/constructor-basic/constructor-basic.model.js
  modules/constructor/constructor-basic/constructor-basic.resolves.js
  modules/constructor/constructor-bottom/constructor-bottom.model.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.model.js
  modules/constructor/constructor.services.js
  modules/currency/__mocks__/currency.utils.js
  modules/currency/currency.service.js
  modules/material/material.service.js
  modules/model/model.service.js
  tests/constructor-basic/constructor-basic.mutation.test.js
  tests/constructor-basic/constructor-basic.query.test.js
  tests/constructor-basic/constructor-basic.variables.js
Labels: BackEnd, test

#426 add filter for constructor model
  modules/model/model.permission.js
  modules/model/model.resolver.js
  modules/model/model.service.js
  typeDefs.js
Labels: Subtask

#439 Imported createColor function from materials.variables.js and removed from constructor.variables.js
  tests/constructor-basic/constructor-basic.query.test.js
  tests/constructor-basic/constructor-basic.variables.js
Labels: BackEnd, test

#437 Order tests
  .eslintrc
  modules/material/material.service.js
  modules/upload/__mocks__/upload.service.js
  tests/category/category.helper.js
  tests/closure/closure.helper.js
  tests/color/color.helper.js
  tests/constructor-basic/constructor-basic.helper.js
  tests/materials/material.helper.js
  tests/model/model.helper.js
  tests/order/order.helpers.js
  tests/order/order.mutation.test.js
  tests/order/order.query.test.js
  tests/order/order.variables.js
  tests/pattern/pattern.helper.js
  tests/product/product.helper.js
  tests/size/size.helper.js
Labels: BackEnd, test

#445 Constructor basic tests
  tests/constructor-basic/constructor-basic.helper.js
  tests/constructor-basic/constructor-basic.mutation.test.js
  tests/constructor-basic/constructor-basic.query.test.js
  tests/constructor-basic/constructor-basic.variables.js
Labels: BackEnd, refactoring, test

#447 Product/Order/Material little fixes
  modules/material/material.graphql.js
  modules/material/material.model.js
  modules/order/order.service.js
  modules/product/product.graphql.js
  modules/product/product.model.js
  modules/product/product.service.js
  resolvers.js
Labels: BackEnd, DB, refactoring

#448 Tests for color and size
  modules/size/size.service.js
  tests/color/color.helper.js
  tests/color/color.mutations.test.js
  tests/color/color.query.test.js
  tests/color/color.variables.js
  tests/size/size.helper.js
  tests/size/size.mutations.test.js
  tests/size/size.queries.test.js
  tests/size/size.variables.js
Labels: BackEnd, test

#454 little fix on materials test
  modules/material/material.model.js
  tests/materials/material.helper.js
  tests/materials/material.variables.js
Labels: BackEnd, test

#452 fix order input test datas
  tests/order/order.variables.js
Labels: BackEnd, bug, test

#458 Test models
  modules/model/model.resolver.js
  modules/model/model.service.js
  tests/model/model.mutation.test.js
  tests/model/model.query.test.js
  tests/model/model.variables.js
Labels: BackEnd, Fixes needed, test

#455 Constructor basic tests
  tests/constructor-basic/constructor-basic.mutation.test.js
  tests/constructor-basic/constructor-basic.query.test.js
  tests/constructor-basic/constructor-basic.variables.js
Labels: BackEnd, bug, test

#461 Fixed tests for sizes
  tests/size/size.helper.js
  tests/size/size.mutations.test.js
  tests/size/size.queries.test.js
  tests/size/size.variables.js
Labels: BackEnd, bug, test

#466 remove useless method
  modules/product/product.resolver.js
  modules/product/product.service.js
  typeDefs.js
Labels: DB

#459 Order tests
  modules/material/material.graphql.js
  tests/order/order.variables.js
Labels: BackEnd, Fixes needed

#463 Fix constructor bottom
  .eslintrc
  modules/constructor/constructor-bottom/constructor-bottom.resolver.js
  tests/constructor-bottom/constructor-bottom.helper.js
  tests/constructor-bottom/constructor-bottom.mutation.test.js
  tests/constructor-bottom/constructor-bottom.query.test.js
  tests/constructor-bottom/constructor-bottom.variables.js
  typeDefs.js
Labels: BackEnd, bug, test

#469 refactored and fixed product tests
  modules/product/product.service.js
  tests/product/product.helper.js
  tests/product/product.mutation.test.js
  tests/product/product.query.test.js
  tests/product/product.variables.js
Labels: BackEnd, refactoring, test

#465 fix news test
  modules/news/news.service.js
  tests/news/news.helper.js
  tests/news/news.mutation.test.js
  tests/news/news.query.test.js
  tests/news/news.variables.js
Labels: refactoring

#467 Fix constructor front
  tests/constructor-front/constructor.front.helper.js
  tests/constructor-front/constructor.mutation.test.js
  tests/constructor-front/constructor.query.test.js
  tests/constructor-front/constructor.variables.js
Labels: BackEnd, bug, test

#470 Fixed comment tests
  modules/comment/comment.service.js
  modules/product/product.resolver.js
  modules/product/product.service.js
  tests/comment/comment.mutations.test.js
  tests/comment/comment.query.test.js
  tests/comment/comment.variables.js
  typeDefs.js
Labels: BackEnd, Fixes needed, test

#476 Hotfix/model add
  modules/model/model.graphql.js
Labels: BackEnd, bug
