Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-12, with the labels that each got.

#954 News text maximum length changed
  validators/language.validator.js
  validators/material.validator.js
  validators/news.validator.js
Labels: refactoring, BackEnd

#956 Fix phone validation in Checkout and user
  consts/regexp.js
  modules/user/user.model.js
Labels: bug, BackEnd

#963 Redesign/950/confirm email
  email-templates/confirm-email-en.pug
  email-templates/confirm-email-ua.pug
  email-templates/css/confirm-email.css
  email-templates/css/main.css
  email-templates/template-en.pug
  email-templates/template-ua.pug
Labels: BackEnd, redesign

#966 redesign /958/redesign recover password
  email-templates/confirm-email-en.pug
  email-templates/confirm-email-ua.pug
  email-templates/css/confirm-email-and-recover-password.css
  email-templates/css/confirm-email.css
  email-templates/recover-password-en.pug
  email-templates/recover-password-ua.pug
Labels: BackEnd, redesign

#967 Redesign of blocked and unlocked emails
  email-templates/block-user-en.pug
  email-templates/block-user-ua.pug
  email-templates/css/main.css
  email-templates/unlock-user-en.pug
  email-templates/unlock-user-ua.pug
Labels: BackEnd, redesign

#970 Redesign of successful verified Mail to the new design on BE
  email-templates/css/main.css
  email-templates/img/email-templates.jpg
  email-templates/successful-confirm-en.pug
  email-templates/successful-confirm-ua.pug
  email-templates/template-en.pug
  email-templates/template-ua.pug
Labels: BackEnd

#976 Redesign/974/redesign email templates
  email-templates/css/main.css
  email-templates/recover-password-en.pug
  email-templates/unlock-user-ua.pug
Labels: BackEnd

#978 Questions/answers/962
  consts/db-collections-names.js
  modules/questions-answers/questions-answers.graphql.js
  modules/questions-answers/questions-answers.model.js
  modules/questions-answers/questions-answers.permissions.js
  modules/questions-answers/questions-answers.resolver.js
  modules/questions-answers/questions-answers.service.js
  permissions.js
  resolvers.js
  tests/questions-answers/questions-answers.helper.js
  tests/questions-answers/questions-answers.mutation.test.js
  tests/questions-answers/questions-answers.query.test.js
  tests/questions-answers/questions-answers.variables.js
  typeDefs.js
Labels: BackEnd

#979 Feature/883/clear logs
  helpers/cron-job/clear-logs-in-mongodb.js
  helpers/cron-job/index.js
Labels: DB, BackEnd, clearLogs

#972 Feature/1387/facebook auth
  consts/index.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  tests/user/user.helper.js
  tests/user/user.mutation.test.js
  tests/user/user.query.test.js
  tests/user/user.variables.js
  typeDefs.js
Labels: BackEnd, login

#984 hotfix/cronPeriod
  helpers/cron-job/clear-logs-in-mongodb.js
Labels: bug

#998 Bug/994/verified purchase icon
  modules/helper-functions.js
Labels: bug, BackEnd

#987 bugfix/708/priceFilter
  modules/product/product.service.js
Labels: bug

#1002 change order validator
  validators/order.validator.js
Labels: BackEnd
