Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-04, with the labels that each got.

#596 fix filters
  helpers/cron-job/remember-about-unfinished-cart-operations.js
  helpers/filter-helper.js
  modules/cart/cart.service.js
  modules/user/user.service.js
  typeDefs.js
Labels: BackEnd, bug

#605 Fix order validations #604
  validators/order.validator.js
Labels: bug

#606 Implement history service
  consts/db-collections-names.js
  consts/history-actions.js
  consts/history-obj-keys.js
  consts/languages.js
  helpers/cron-job/unlock-users.js
  modules/cart/cart.permissions.js
  modules/cart/cart.resolver.js
  modules/cart/cart.service.js
  modules/category/category.resolver.js
  modules/category/category.service.js
  modules/closures/closures.resolver.js
  modules/closures/closures.service.js
  modules/color/color.resolver.js
  modules/color/color.service.js
  modules/header/header.resolver.js
  modules/header/header.service.js
  modules/history/history.graphql.js
  modules/history/history.model.js
  modules/history/history.permissions.js
  modules/history/history.resolvers.js
  modules/history/history.service.js
  modules/material/material.resolver.js
  modules/material/material.service.js
  modules/news/news.resolver.js
  modules/news/news.service.js
  modules/pattern/pattern.resolver.js
  modules/pattern/pattern.service.js
  modules/product/product.permissions.js
  modules/product/product.resolver.js
  modules/product/product.service.js
  modules/size/size.resolver.js
  modules/size/size.service.js
  modules/user/user.service.js
  package-lock.json
  package.json
  permissions.js
  resolvers.js
  typeDefs.js
  utils/hisrory.js
Labels: BackEnd, DB, Task

#607 Feature/612
  consts/email-actions.js
  consts/index.js
  email-templates/confirm-creation-superadmin-email.pug
  email-templates/css/main.css
  email-templates/index.js
  error-messages/user.messages.js
  modules/business-text/business-text.service.js
  modules/user/user.graphql.js
  modules/user/user.model.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  package-lock.json
  tests/user/user.mutation.test.js
  tests/user/user.query.test.js
  tests/user/user.variables.js
  typeDefs.js
  validators/user.validator.js
Labels: BackEnd

#601 Add pug page for incomplete operations in cart and payment order
  consts/cron-period.js
  consts/email-actions.js
  email-templates/css/main.css
  email-templates/incomplete-operations.pug
  email-templates/index.js
  email-templates/payment-order.pug
  helpers/cron-job/remember-about-unfinished-cart-operations.js
  helpers/cron-job/unlock-users.js
  modules/payment/payment.service.js
Labels: BackEnd

#576 Added model joi validation
  consts/input-fields.js
  modules/model/model.permission.js
  tests/model/model.mutation.test.js
  tests/model/model.query.test.js
  validators/model.validator.js
Labels: BackEnd, DB

#610 add get by id method in history service
  error-messages/history.js
  modules/history/history.permissions.js
  modules/history/history.resolvers.js
  modules/history/history.service.js
  resolvers.js
  typeDefs.js
Labels: BackEnd, Fixes needed

#602 refactored method " add order" and "update order"
  modules/order/order.service.js
  utils/order.utils.js
Labels: BackEnd, DB

#612 add Joi validation for size service methods
  error-messages/size.messages.js
  modules/size/size.model.js
  modules/size/size.permissions.js
  validators/size.validator.js
Labels: BackEnd, DB

#619 Feature/589
  error-messages/home-page-messages.js
  modules/business-text/business-text.permissions.js
  modules/comment/comment.permissions.js
  modules/currency/currency.permission.js
  modules/email-chat/email-chat.permission.js
  modules/homepage-images/home-page-images.permissions.js
  modules/homepage-slider/homepage-slider.permission.js
  modules/material/material.permissions.js
  modules/order/order.permissions.js
  modules/upload/upload.permission.js
  modules/user/user.permissions.js
  permissions.js
  tests/homepage-images/homepage-images.mutation.test.js
  tests/user/user.query.test.js
Labels: BackEnd, DB

#621 Hotfix/579
  error-messages/user.messages.js
  modules/header/header.permisions.js
  modules/order/order.permissions.js
  modules/user/user.resolver.js
  modules/user/user.service.js
Labels: BackEnd, bug

#628 hotfix
  modules/homepage-images/home-page-images.permissions.js
  modules/user/user.graphql.js
  modules/user/user.service.js
  tests/homepage-images/homepage-images.mutation.test.js
  tests/user/user.mutation.test.js
  typeDefs.js
Labels: BackEnd, bug
