Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-11, with the labels that each got.

#916 Refactor/913/pattern
  modules/pattern/pattern.graphql.js
  modules/pattern/pattern.model.js
  modules/pattern/pattern.service.js
Labels: refactoring, BackEnd

#918 added translations for closures
  modules/closures/closures.graphql.js
  modules/closures/closures.model.js
  modules/closures/closures.service.js
Labels: refactoring, BackEnd

#919 add translation to business-page
  modules/business-text/business-text.graphql.js
  modules/business-text/business-text.model.js
  modules/business-text/business-text.service.js
Labels: refactoring, BackEnd

#915 914/refactoring/Product filter by size price
  modules/product/product.service.js
  tests/product/product.variables.js
Labels: BackEnd

#927 923/New color translation
  modules/color/color.graphql.js
  modules/color/color.model.js
  modules/color/color.service.js
Labels: refactoring, BackEnd

#920 Refactor/910/add translations for categories
  modules/category/category.graphql.js
  modules/category/category.model.js
  modules/category/category.service.js
  typeDefs.js
Labels: refactoring, BackEnd

#935 Fixed translations key for bussiness pages
  modules/business-text/business-text.graphql.js
  modules/business-text/business-text.model.js
  modules/business-text/business-text.service.js
Labels: refactoring, BackEnd

#929 926/Header and homepage-slider translations
  error-messages/header.messages.js
  modules/header/header.graphql.js
  modules/header/header.model.js
  modules/header/header.permisions.js
  modules/header/header.resolver.js
  modules/header/header.service.js
  modules/homepage-slider/homepage-slider.graphql.js
  modules/homepage-slider/homepage-slider.model.js
  modules/homepage-slider/homepage-slider.service.js
  permissions.js
  resolvers.js
  tests/header/header.helper.js
  tests/header/header.mutations.test.js
  tests/header/header.query.test.js
  tests/header/header.variables.js
  tests/homepage-slider/homepage-slider.mutation.test.js
  typeDefs.js
  validators/header.validator.js
Labels: refactoring, BackEnd

#933 added fields for couirer be part
  validators/order.validator.js
Labels: BackEnd

#931 Refactor/928/news
  modules/news/news.graphql.js
  modules/news/news.model.js
  modules/news/news.service.js
  modules/order/order.service.js
Labels: refactoring, BackEnd

#936 refactor model
  modules/category/category.service.js
  modules/model/model.graphql.js
  modules/model/model.model.js
  modules/model/model.service.js
  tests/model/model.mutation.test.js
  tests/model/model.query.test.js
  tests/model/model.variables.js
  typeDefs.js
Labels: BackEnd

#921 refactor materials 906
  modules/material/material.graphql.js
  modules/material/material.model.js
  modules/material/material.service.js
Labels: refactoring, BackEnd

#938 Fixed translations-key
  modules/pattern/pattern.graphql.js
  modules/pattern/pattern.model.js
  modules/pattern/pattern.service.js
Labels: bug, BackEnd

#940 hotfix delivery fields
  validators/order.validator.js
Labels: bug

#934 Refactor/925/refactor translations back, basics, bottoms, pocket, strap and position
  modules/back/back.graphql.js
  modules/back/back.model.js
  modules/back/back.service.js
  modules/basics/basics.graphql.js
  modules/basics/basics.model.js
  modules/basics/basics.resolver.js
  modules/basics/basics.service.js
  modules/bottom/bottom.graphql.js
  modules/bottom/bottom.model.js
  modules/bottom/bottom.service.js
  modules/pocket/pocket.graphql.js
  modules/pocket/pocket.model.js
  modules/pocket/pocket.service.js
  modules/position/position.graphql.js
  modules/position/position.model.js
  modules/position/position.service.js
  modules/strap/strap.graphql.js
  modules/strap/strap.model.js
  modules/strap/strap.service.js
  tests/back/back.helper.js
  tests/basics/basics.helper.js
  tests/bottom/bottom.helper.js
  tests/pocket/pocket.helper.js
  tests/position/position.helpers.js
  tests/strap/strap.helper.js
  tests/strap/strap.mutation.test.js
  tests/strap/strap.variables.js
Labels: refactoring, BackEnd

#943 Feature/941/New-query-UkrPoshtaStreet
  consts/index.js
  modules/delivery/ukr-poshta/ukr-poshta.graphql.js
  modules/delivery/ukr-poshta/ukr-poshta.resolver.js
  modules/delivery/ukr-poshta/ukr-poshta.service.js
  tests/delivery/ukr-poshta/ukr-poshta.helper.js
  tests/delivery/ukr-poshta/ukr-poshta.query.test.js
  tests/delivery/ukr-poshta/ukr-poshta.variables.js
  typeDefs.js
  validators/order.validator.js
Labels: BackEnd

#948 Hotfix/1277/codesmell regex be
  consts/regexp.js
Labels: BackEnd

#949 Fixed logger regex codesmell
  .gitignore
  logger.js
Labels: BackEnd

#947 Hotfix/1277/security hotspost
  consts/regexp.js
Labels: BackEnd

#922 Bugfix/1107/pattern/be
  modules/pattern/pattern.service.js
  tests/pattern/pattern.helper.js
  tests/pattern/pattern.mutation.test.js
Labels: bug, BackEnd
