Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-10, with the labels that each got.

#875 Eslint fix console log
  .eslintrc
  dump-database.js
Labels: BackEnd, eslint

#881 Add functionality to regexp password that allow to write special characters
  consts/regexp.js
  tests/user/user.variables.js
Labels: bug, BackEnd

#898 897/feature Added translations to contacts on be
  modules/contact/contact.graphql.js
  modules/contact/contact.model.js
  modules/contact/contact.service.js
  server.js
  utils/createTranslations.js
Labels: enhancement, BackEnd
