Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-09, with the labels that each got.

#770 Create Basics DB
  consts/basics-messages.js
  consts/db-collections-names.js
  consts/history-actions.js
  consts/input-fields.js
  modules/basics/basics.graphql.js
  modules/basics/basics.model.js
  modules/basics/basics.permissions.js
  modules/basics/basics.resolver.js
  modules/basics/basics.service.js
  permissions.js
  resolvers.js
  tests/basics/basics.helper.js
  tests/basics/basics.mutation.test.js
  tests/basics/basics.query.test.js
  tests/basics/basics.variables.js
  typeDefs.js
  utils/constructorOptionCommonFilters.js
  validators/constructor-items-inputs.validator.js
Labels: BackEnd, constructor

#803 Increase tests coverage for orders module
  modules/order/order.resolver.js
  modules/order/order.service.js
  tests/order/order.helpers.js
  tests/order/order.query.test.js
  tests/order/order.variables.js
Labels: test, BackEnd

#825 fix CI pipeline
  .github/workflows/main.yml
  .gitignore
  package-lock.json
  package.json
Labels: bug, priority: high, devops, BackEnd

#812 Returned figure scopes for filter
  modules/order/order.service.js
Labels: bug, BackEnd

#830 795/tests/upload test
  tests/upload/TestImage.png
  tests/upload/upload.helper.js
  tests/upload/upload.mutations.test.js
  tests/upload/upload.utils.test.js
  tests/upload/upload.variables.js
Labels: test, BackEnd

#800 Write tests for pockets
  modules/pocket/pocket.permissions.js
  modules/pocket/pocket.resolver.js
  modules/pocket/pocket.service.js
  tests/pocket/pocket.helper.js
  tests/pocket/pocket.mutation.test.js
  tests/pocket/pocket.query.test.js
  tests/pocket/pocket.variables.js
  typeDefs.js
Labels: test, BackEnd

#759 created bottom module and covered it with tests
  consts/constructor-option-types.js
  consts/cron-period.js
  consts/db-collections-names.js
  consts/history-actions.js
  consts/index.js
  consts/input-fields.js
  error-messages/bottom-messages.js
  models/AdditionalCurrencySet.js
  modules/bottom/bottom.graphql.js
  modules/bottom/bottom.model.js
  modules/bottom/bottom.permissions.js
  modules/bottom/bottom.resolver.js
  modules/bottom/bottom.service.js
  modules/material/material.model.js
  modules/model/model.graphql.js
  modules/model/model.model.js
  modules/pattern/pattern.model.js
  modules/size/size.model.js
  permissions.js
  resolvers.js
  tests/bottom/bottom.helper.js
  tests/bottom/bottom.mutation.test.js
  tests/bottom/bottom.query.test.js
  tests/bottom/bottom.variables.js
  typeDefs.js
  validators/additional-price-input.validators.js
  validators/constructor-items-inputs.validator.js
  validators/model.validator.js
  validators/size.validator.js
Labels: DB, BackEnd

#838 Hotfix/file upload
  Dockerfile
  package-lock.json
Labels: devops, BackEnd

#839 add package-lock.json to gitignore
  .gitignore
Labels: devops, BackEnd

#846 805/tests Writed tests for Ukr Poshta delivery
  tests/delivery/ukr-poshta/ukr-poshta.helper.js
  tests/delivery/ukr-poshta/ukr-poshta.query.test.js
  tests/delivery/ukr-poshta/ukr-poshta.service.test.js
  tests/delivery/ukr-poshta/ukr-poshta.variables.js
Labels: test, BackEnd

#845 tests/708 Writed tests for Nova Poshta Delivery
  tests/delivery/nova-poshta/nova-poshta.helper.js
  tests/delivery/nova-poshta/nova-poshta.service.test.js
  tests/delivery/nova-poshta/nova-poshta.variables.js
  tests/delivery/nova-poshta/nova.poshta.query.test.js
Labels: test, BackEnd

#649 added material and news JOI validation
  consts/input-fields.js
  modules/material/material.permissions.js
  modules/news/news.permissions.js
  tests/news/news.variables.js
  validators/language.validator.js
  validators/material.validator.js
  validators/news.validator.js
Labels: BackEnd

#843 833/refactoring Refactored strap module
  modules/strap/strap.graphql.js
  modules/strap/strap.model.js
  modules/strap/strap.permissions.js
  modules/strap/strap.resolver.js
  modules/strap/strap.service.js
  tests/strap/strap.helper.js
  tests/strap/strap.mutation.test.js
  tests/strap/strap.query.test.js
  tests/strap/strap.variables.js
  validators/constructor-items-inputs.validator.js
Labels: refactoring, BackEnd

#850 add dump-database.js to test exclusion
  jest.config.js
  sonar-project.properties
Labels: test, devops, BackEnd

#840 changed price from Int to Float and made some fixes
  helpers/calculateCartTotalSum.js
  modules/cart/cart.resolver.js
  modules/cart/cart.service.js
  modules/order/order.graphql.js
  modules/order/order.service.js
  modules/user/user.graphql.js
  tests/cart/cart.helper.js
  tests/cart/cart.mutation.test.js
  tests/cart/cart.query.test.js
  tests/cart/cart.variables.js
  tests/order/order.variables.js
  typeDefs.js
  utils/order.utils.js
  validators/order.validator.js
Labels: bug, BackEnd

#862 Fix currency for basic and back
  migrations/20210917061700-change-additional-price-back.js
  modules/back/back.graphql.js
  modules/back/back.model.js
  modules/back/back.permissions.js
  modules/back/back.service.js
  tests/back/back.helper.js
  tests/back/back.variables.js
  validators/constructor-items-inputs.validator.js
Labels: bug, BackEnd

#864 1019 refactoring Refactored models aphabetic sort
  modules/model/model.service.js
Labels: refactoring, BackEnd

#858 added lowercase to email
  modules/user/user.model.js
  tests/user/user.query.test.js
Labels: BackEnd

#860 820/feature Writed database collection for constructor
  consts/db-collections-names.js
  consts/history-actions.js
  consts/input-fields.js
  error-messages/constructor.messages.js
  modules/constructor_new/constructor.graphql.js
  modules/constructor_new/constructor.model.js
  modules/constructor_new/constructor.permissions.js
  modules/constructor_new/constructor.resolver.js
  modules/constructor_new/constructor.service.js
  permissions.js
  resolvers.js
  tests/constructor-new/constructor.helper.js
  tests/constructor-new/constructor.mutation.test.js
  tests/constructor-new/constructor.query.test.js
  tests/constructor-new/constructor.variables.js
  typeDefs.js
  validators/constructor-items-inputs.validator.js
Labels: enhancement, BackEnd

#861 855/refactoring/refactor be restrictions for constructor
  modules/constructor_new/constructor.graphql.js
  modules/constructor_new/constructor.model.js
  resolvers.js
  tests/constructor-new/constructor.variables.js
  validators/constructor-items-inputs.validator.js
Labels: refactoring, BackEnd

#866 794 Payment module tests
  tests/payment/payment.helper.js
  tests/payment/payment.query.test.js
Labels: test, BackEnd

#870 fix delete product
  modules/product/product.service.js
Labels: BackEnd

#869 Increase test coverage for model module (new branch and new repo)
  modules/model/model.service.js
  tests/model/model.helper.js
  tests/model/model.mutation.test.js
Labels: test, BackEnd

#874 update user
  modules/user/user.graphql.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  typeDefs.js
Labels: BackEnd
