Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-05, with the labels that each got.

#632 fix length product description
  validators/product.validator.js
Labels: BackEnd, Fixes needed

#636 add filters
  consts/date-range.js
  helpers/filter-helper.js
  modules/category/category.resolver.js
  modules/category/category.service.js
  modules/comment/comment.graphql.js
  modules/comment/comment.service.js
  modules/history/history.model.js
  modules/history/history.service.js
  modules/material/material.graphql.js
  modules/material/material.service.js
  modules/news/news.graphql.js
  modules/news/news.service.js
  modules/order/order.graphql.js
  modules/order/order.service.js
  modules/product/product.service.js
  modules/size/size.graphql.js
  modules/size/size.resolver.js
  modules/size/size.service.js
  modules/user/user.graphql.js
  modules/user/user.service.js
  tests/news/news.helper.js
  tests/news/news.query.test.js
  tests/size/size.helper.js
  tests/user/user.query.test.js
  typeDefs.js
Labels: BackEnd, Task

#648 add reply comments method
  consts/date-range.js
  consts/input-fields.js
  error-messages/comment.messages.js
  migrations/20210518065842-add-column-reply-comments-to-comment-collection.js
  modules/cart/cart.service.js
  modules/comment/comment.graphql.js
  modules/comment/comment.model.js
  modules/comment/comment.permissions.js
  modules/comment/comment.resolver.js
  modules/comment/comment.service.js
  modules/history/history.service.js
  modules/order/order.service.js
  modules/product/product.service.js
  modules/user/user.service.js
  resolvers.js
  tests/comment/comment.helper.js
  tests/comment/comment.query.test.js
  tests/order/order.helpers.js
  typeDefs.js
  validators/comment.validator.js
Labels: BackEnd, DB, Task

#650 Add validation for Contact inputs on BE
  consts/input-fields.js
  consts/ranges.js
  modules/contact/contact.model.js
  modules/contact/contact.permission.js
  tests/contact/__snapshots__/contact.query.test.js.snap
  tests/contact/contact.variables.js
  validators/contact.validator.js
Labels: BackEnd

#655 fix model bug
  modules/model/model.service.js
Labels: BackEnd, bug

#653 added slug to the news
  consts/migrations.js
  consts/transliteration.js
  modules/helper-functions.js
  modules/news/news.graphql.js
  modules/news/news.model.js
  modules/news/news.service.js
Labels: BackEnd, DB

#647 fixed confirmUser method
  error-messages/user.messages.js
  helpers/tokenChecker.js
  modules/news/news.service.js
  modules/user/user.graphql.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  package-lock.json
  package.json
  typeDefs.js
Labels: BackEnd, Fixes needed

#660 Added extra migrations and fixed existing ones
  consts/migrations.js
  migrations/20210418172905-add-fields-to-closures.js
  migrations/20210418181215-update-fields-in-patterns.js
  migrations/20210418184317-update-fields-in-constructorBasic.js
  migrations/20210418203406-update-fields-in-constructorBottom.js
  migrations/20210418204054-update-fields-in-constructorFrontPockets.js
  migrations/20210418204846-update-fields-in-models.js
  migrations/20210526200334-update-fields-in-remaining-constructorBasics.js
Labels: BackEnd, DB
