Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-08, with the labels that each got.

#734 Hotfix/hisrory
  helpers/cron-job/unlock-users.js
  modules/back/back.service.js
  modules/category/category.service.js
  modules/closures/closures.service.js
  modules/color/color.service.js
  modules/constructor/constructor.services.js
  modules/header/header.service.js
  modules/material/material.service.js
  modules/model/model.service.js
  modules/news/news.service.js
  modules/pattern/pattern.service.js
  modules/pocket/pocket.service.js
  modules/position/position.service.js
  modules/product/product.service.js
  modules/restriction/restriction.service.js
  modules/size/size.service.js
  modules/strap/strap.service.js
  modules/user/user.service.js
  test-error.log
  utils/history.js
Labels: bug

#746 Master hotfix / Test falling
  tests/materials/material.query.test.js
  tests/pattern/pattern.query.test.js
Labels: bug, test

#749 added tests for positions
  resolvers.js
  tests/position/position.helpers.js
  tests/position/position.mutation.test.js
  tests/position/position.query.test.js
  tests/position/position.variables.js
Labels: BackEnd, test

#761 fixed 50 eslint warnings
  modules/size/size.model.js
  tests/cart/cart.mutation.test.js
  tests/cart/cart.query.test.js
  tests/closure/closure.mutation.test.js
  tests/closure/closure.query.test.js
  tests/comment/comment.mutations.test.js
  tests/comment/comment.query.test.js
  tests/constructor-basic/constructor-basic.mutation.test.js
  tests/constructor-basic/constructor-basic.query.test.js
  tests/constructor-bottom/constructor-bottom.mutation.test.js
  tests/constructor-bottom/constructor-bottom.query.test.js
  tests/constructor-front/constructor.mutation.test.js
  tests/constructor-front/constructor.query.test.js
  tests/history/history.query.test.js
  tests/homepage-slider/homepage-slider.query.test.js
  tests/logger/logger.query.test.js
  tests/materials/material.query.test.js
  tests/materials/material.variables.js
  tests/model/model.mutation.test.js
  tests/order/order.mutation.test.js
  tests/pattern/pattern.mutation.test.js
  tests/pattern/pattern.query.test.js
  tests/product/product.query.test.js
  tests/size/size.mutations.test.js
  tests/size/size.queries.test.js
  tests/user/user.query.test.js
  validators/constructor-items-inputs.validator.js
Labels: BackEnd

#760 codesmells fixed
  modules/email-chat/email-chat.resolver.js
Labels: BackEnd

#756 Fix code smells in nova poshta
  modules/delivery/nova-poshta/nova-poshta.resolver.js
  modules/delivery/nova-poshta/nova-poshta.service.js
Labels: BackEnd

#762 Fixed code smells, related to resolvers
  modules/header/header.resolver.js
  modules/homepage-images/home-page-images.resolver.js
  modules/homepage-images/home-page-images.service.js
  modules/homepage-slider/homepage-slider.service.js
  modules/material/material.resolver.js
  modules/modules.service.js
  modules/order/order.resolver.js
  modules/payment/payment.service.js
Labels: BackEnd

#751 fixing codesmells
  modules/contact/contact.service.js
Labels: BackEnd

#777 Change and add new fields in database order.
  consts/migrations.js
  migrations/20210814070350-modify_user_to_recipient_in_order.js
  migrations/20210814081013-add_user_id_fild_to_order.js
  modules/order/order.graphql.js
  modules/order/order.model.js
  modules/order/order.service.js
  modules/payment/payment.service.js
  tests/comment/comment.mutations.test.js
  tests/comment/comment.variables.js
  tests/order/order.helpers.js
  tests/order/order.mutation.test.js
  tests/order/order.query.test.js
  tests/order/order.variables.js
  validators/order.validator.js
Labels: BackEnd

#774 Gmail API mailer
  .github/workflows/main.yml
  dotenvValidator.js
  error-messages/email.messages.js
  modules/user/user.service.js
  package-lock.json
  package.json
  server.js
  tests/mailer/mailer.helper.js
  tests/mailer/mailer.queries.test.js
  tests/mailer/mailer.variables.js
  utils/email-service.js
  utils/mailer.js
Labels: test, BackEnd

#779 info logs Bugfix/772
  server.js
Labels: bug, BackEnd

#778 removed modules.service.js
  modules/modules.service.js
Labels: test, BackEnd

#781 deleted unused file
  modules/modules.service.js
Labels: BackEnd

#786 added skip for mailApi connection verification
  tests/mailer/mailer.queries.test.js
Labels: BackEnd

#784 removed codesmell and deleted unused file
  utils/validate-user.js
Labels: BackEnd

#785 Fix database warnings
  config/db.js
  currency.worker.js
  loggerHttp.js
  server.js
  tests/config.test.app.js
  tests/logger/logger.query.test.js
  tests/logger/logger.variables.js
  utils/email-service.js
Labels: DB, BackEnd

#787 fixed codesmels
  modules/product/product.service.js
  utils/rules.js
Labels: BackEnd

#799 Bug fix fe/825
  modules/user/user.graphql.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  typeDefs.js
  validators/user.validator.js
Labels: bug, BackEnd

#801 added tests for restriction
  tests/restriction/restriction.helper.js
  tests/restriction/restriction.mutation.test.js
  tests/restriction/restriction.query.test.js
  tests/restriction/restriction.variables.js
Labels: test, BackEnd
