Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-07, with the labels that each got.

#691 Fix current codesmells on horondi-be/575
  modules/business-text/business-text.service.js
  modules/category/category.service.js
  modules/color/color.service.js
  modules/contact/contact.service.js
  modules/currency/currency.service.js
  modules/delivery/ukr-poshta/ukr-poshta.service.js
  modules/email-chat/email-chat.service.js
  modules/header/header.service.js
  modules/homepage-images/home-page-images.service.js
  modules/homepage-slider/homepage-slider.service.js
  modules/order/order.service.js
  modules/product/product.service.js
Labels: BackEnd, bug

#694 Modul constructor/add options (pockets)
  consts/constructor-option-types.js
  modules/pocket/pocket.graphql.js
  modules/pocket/pocket.model.js
  modules/pocket/pocket.resolver.js
  modules/pocket/pocket.service.js
  typeDefs.js
  validators/constructor-items-inputs.validator.js
Labels: BackEnd, constructor

#700 Fixed addition of empty fields of images array after product update
  modules/product/product.service.js
Labels: BackEnd, bug

#686 Bug fix/674
  migrations/20210617215314-update-sizes-models-relations.js
  modules/size/size.graphql.js
  modules/size/size.model.js
  modules/size/size.service.js
  resolvers.js
  tests/closure/closure.mutation.test.js
  tests/closure/closure.query.test.js
  tests/comment/comment.mutations.test.js
  tests/comment/comment.query.test.js
  tests/constructor-basic/constructor-basic.mutation.test.js
  tests/constructor-basic/constructor-basic.query.test.js
  tests/constructor-bottom/constructor-bottom.mutation.test.js
  tests/constructor-bottom/constructor-bottom.query.test.js
  tests/constructor-front/constructor.mutation.test.js
  tests/constructor-front/constructor.query.test.js
  tests/history/history.query.test.js
  tests/materials/material.mutation.test.js
  tests/model/model.mutation.test.js
  tests/model/model.query.test.js
  tests/model/model.variables.js
  tests/order/order.mutation.test.js
  tests/order/order.query.test.js
  tests/pattern/pattern.mutation.test.js
  tests/pattern/pattern.query.test.js
  tests/product/product.mutation.test.js
  tests/product/product.query.test.js
  tests/size/size.helper.js
  tests/size/size.mutations.test.js
  tests/size/size.queries.test.js
  tests/size/size.variables.js
  validators/size.validator.js
Labels: BackEnd

#716 fixed problems if additionalPrice=0
  modules/pocket/pocket.service.js
Labels: BackEnd, constructor

#718 fixed problems on Back component if additionalPrice=0 && filters error
  modules/back/back.service.js
  utils/constructorOptionCommonFilters.js
Labels: BackEnd, bug

#693 cart tests 581
  tests/cart/cart.helper.js
  tests/cart/cart.mutation.test.js
  tests/cart/cart.query.test.js
  tests/cart/cart.variables.js
Labels: BackEnd, test

#727 tests/710 [Write test for back module]
  tests/back/back.helper.js
  tests/back/back.mutation.test.js
  tests/back/back.query.test.js
  tests/back/back.variables.js
Labels: BackEnd, test

#703 Bugfix/663 Recovery password
  modules/user/user.service.js
Labels: BackEnd, bug

#724 chat-email module tested 707
  modules/email-chat/email-chat.service.js
  tests/email-chat/email-chat.helper.js
  tests/email-chat/email-chat.mutations.test.js
  tests/email-chat/email-chat.queries.test.js
  tests/email-chat/email-chat.variables.js
Labels: BackEnd, test

#730 Fixed project typos
  consts/index.js
  modules/comment/comment.service.js
  modules/delivery/nova-poshta/nova-poshta.service.js
  modules/helper-functions.js
  modules/order/order.service.js
  modules/user/user.service.js
Labels: bug

#732 Tests/704 [Test cases for STRAP module]
  modules/strap/strap.service.js
  tests/strap/strap.helper.js
  tests/strap/strap.mutation.test.js
  tests/strap/strap.query.test.js
  tests/strap/strap.variables.js
Labels: BackEnd, test

#740 Added position module for Constructor/pockets
  consts/db-collections-names.js
  consts/history-actions.js
  consts/history-obj-keys.js
  consts/input-fields.js
  error-messages/positions.massage.js
  modules/position/position.graphql.js
  modules/position/position.model.js
  modules/position/position.permissions.js
  modules/position/position.resolver.js
  modules/position/position.service.js
  permissions.js
  resolvers.js
  typeDefs.js
  validators/position.validator.js
Labels: BackEnd

#745 Implement positions into pockets/Backend
  consts/constructor-option-types.js
  modules/pocket/pocket.graphql.js
  modules/pocket/pocket.model.js
  resolvers.js
  typeDefs.js
  validators/constructor-items-inputs.validator.js
Labels: BackEnd, constructor

#742 Closures (constructor)
  modules/closures/closures.graphql.js
  modules/closures/closures.model.js
  modules/closures/closures.permission.js
  modules/closures/closures.resolver.js
  modules/closures/closures.service.js
  typeDefs.js
  validators/constructor-items-inputs.validator.js
Labels: BackEnd

#720 added new step into ci
  .github/workflows/main.yml
Labels: BackEnd, devops

#744 Implement logs, using winston (Feature/616)
  .gitignore
  logger.js
  loggerHttp.js
  package-lock.json
  package.json
  server.js
  tests/config.test.app.js
  tests/logger/logger.query.test.js
  tests/logger/logger.variables.js
  utils/format-error.js
Labels: BackEnd, DB, test
