Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-02, with the labels that each got.

#489 Fixed codesmells on backend services
  modules/business-text/business-text.service.js
  modules/category/category.service.js
  modules/closures/closures.service.js
  modules/color/color.service.js
  modules/comment/comment.service.js
  modules/contact/contact.service.js
  modules/currency/currency.service.js
  modules/currency/currency.utils.js
  modules/email-chat/email-chat.resolver.js
  modules/email-chat/email-chat.service.js
  modules/header/header.service.js
  modules/homepage-images/home-page-images.service.js
  modules/homepage-slider/homepage-slider.service.js
  modules/material/material.service.js
  modules/model/model.service.js
  modules/news/news.service.js
  modules/order/order.service.js
  modules/pattern/pattern.service.js
  modules/product/product.service.js
  modules/size/size.service.js
  modules/user/user.service.js
  tests/comment/comment.mutations.test.js
  tests/comment/comment.query.test.js
Labels: BackEnd, Fixes needed

#487 Refactor comments schema and service
  error-messages/comment.messages.js
  modules/comment/comment.graphql.js
  modules/comment/comment.model.js
  modules/comment/comment.permissions.js
  modules/comment/comment.resolver.js
  modules/comment/comment.service.js
  permissions.js
  resolvers.js
  tests/comment/__snapshots__/comment.query.test.js.snap
  tests/comment/comment.helper.js
  tests/comment/comment.mutations.test.js
  tests/comment/comment.query.test.js
  tests/comment/comment.variables.js
  tests/user/user.helper.js
  typeDefs.js
Labels: BackEnd, DB

#494 fix pattern and material schema
  modules/material/material.graphql.js
  modules/material/material.model.js
  modules/pattern/pattern.graphql.js
  modules/pattern/pattern.model.js
Labels: BackEnd, Fixes needed

#479 add methods for getting all product combinations
  modules/category/category.graphql.js
  modules/category/category.resolver.js
  modules/category/category.service.js
  modules/closures/closures.resolver.js
  modules/material/material.graphql.js
  modules/material/material.resolver.js
  modules/material/material.service.js
  modules/product/product.graphql.js
  modules/product/product.service.js
  typeDefs.js
Labels: Task

#501 refactor pattern resolver
  resolvers.js
Labels: Fixes needed

#495 refactor MaterialByPorpose type
  modules/material/material.graphql.js
Labels: BackEnd, Fixes needed

#500 make new method for product filtering
  modules/product/product.graphql.js
  modules/product/product.resolver.js
  modules/product/product.service.js
  resolvers.js
  typeDefs.js
Labels: BackEnd

#352 Order and payment service
  error-messages/orders.messages.js
  models/Delivery.js
  modules/helper-functions.js
  modules/order/order.graphql.js
  modules/order/order.service.js
  modules/payment/payment.resolver.js
  modules/payment/payment.service.js
  utils/order.utils.js
Labels: BackEnd, WIP, refactoring

#508 Bugfix/576
  modules/comment/comment.resolver.js
  modules/comment/comment.service.js
  tests/comment/comment.helper.js
  tests/comment/comment.query.test.js
  tests/comment/comment.variables.js
  typeDefs.js
Labels: BackEnd, Fixes needed

#509 fix test for comments
  modules/comment/comment.graphql.js
  tests/comment/comment.helper.js
  tests/comment/comment.mutations.test.js
  tests/comment/comment.variables.js
  typeDefs.js
Labels: BackEnd

#505 rewrite upload images from base64 in database to link on blobStorage
  modules/constructor/constructor-basic/constructor-basic.resolves.js
  modules/constructor/constructor-bottom/constructor-bottom.resolver.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.resolves.js
  modules/constructor/constructor.services.js
  modules/pattern/pattern.service.js
  modules/upload/upload.utils.js
  tests/pattern/pattern.helper.js
  tests/pattern/pattern.mutation.test.js
  tests/pattern/pattern.variables.js
  typeDefs.js
Labels: BackEnd, refactoring

#504 Category filter-sort-search
  helpers/filter-helper.js
  modules/category/category.graphql.js
  modules/category/category.resolver.js
  modules/category/category.service.js
  modules/user/user.service.js
  package-lock.json
  tests/category/category.helper.js
  typeDefs.js
Labels: BackEnd, Fixes needed

#522 Refactored getAllComments for future filter functionality
  modules/comment/comment.service.js
  typeDefs.js
Labels: BackEnd, refactoring

#524 Fix getAllComments for searching
  helpers/filter-helper.js
  modules/comment/comment.service.js
  typeDefs.js
Labels: BackEnd

#525 added Simple name field for sizes and fix tests
  error-messages/size.messages.js
  modules/size/size.graphql.js
  modules/size/size.service.js
  tests/size/size.helper.js
  tests/size/size.mutations.test.js
  tests/size/size.variables.js
Labels: BackEnd, refactoring

#510 commit
  consts/regexp.js
  error-messages/address.messages.js
  error-messages/business-text.messages.js
  error-messages/category.messages.js
  error-messages/color.massage.js
  error-messages/common.messages.js
  error-messages/image.messages.js
  error-messages/size.messages.js
  models/Language.js
  modules/business-text/business-text.model.js
  modules/category/category.model.js
  modules/color/color.model.js
  modules/comment/comment.model.js
  modules/comment/common/Address.js
  modules/comment/common/ImageSet.js
  modules/common/Address.js
  modules/constructor/constructor-basic/constructor-basic.model.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.model.js
  modules/contact/contact.model.js
  modules/email-chat/email-chat.model.js
  modules/homepage-slider/homepage-slider.model.js
  modules/order/order.model.js
  modules/size/size.model.js
  modules/user/user.model.js
  tests/category/category.mutation.test.js
  tests/category/category.query.test.js
  tests/comment/comment.mutations.test.js
  tests/comment/comment.query.test.js
  tests/constructor-basic/constructor-basic.mutation.test.js
  tests/constructor-basic/constructor-basic.query.test.js
  tests/constructor-bottom/constructor-bottom.mutation.test.js
  tests/constructor-bottom/constructor-bottom.query.test.js
  tests/contact/__snapshots__/contact.query.test.js.snap
  tests/contact/contact.variables.js
  tests/size/size.mutations.test.js
  tests/size/size.queries.test.js
  tests/user/user.mutation.test.js
  tests/user/user.query.test.js
Labels: BackEnd

#528 fix delivery model and order graphql types
  consts/currency.js
  consts/delivery-type.js
  error-messages/common.messages.js
  models/Delivery.js
  modules/order/order.graphql.js
  modules/order/order.model.js
  tests/order/order.helpers.js
  tests/order/order.variables.js
  utils/order.utils.js
Labels: BackEnd, Fixes needed

#532 Delete courierOficeName prop from delivery schema
  models/Delivery.js
  modules/order/order.graphql.js
Labels: BackEnd, Fixes needed

#529 add price to products filters
  modules/product/product.graphql.js
  modules/product/product.service.js
Labels: BackEnd
