Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-03, with the labels that each got.

#547 refactored magic strings and took them out to consts
  consts/comments-operations.js
  consts/db-collections-names.js
  consts/delivery-services.js
  consts/email-statuses.js
  consts/file-sizes.js
  consts/locations.js
  consts/map-images-indecies.js
  consts/payments.js
  consts/ranges.js
  consts/request-methods.js
  consts/status-codes.js
  models/Background.js
  models/BusinessText.js
  models/Closure.js
  models/CurrencySet.js
  models/Delivery.js
  models/Language.js
  models/OrderItem.js
  models/PrimaryImage.js
  modules/business-text/business-text.model.js
  modules/business-text/business-text.resolver.js
  modules/business-text/business-text.service.js
  modules/category/category.model.js
  modules/category/category.resolver.js
  modules/closures/closures.model.js
  modules/closures/closures.resolver.js
  modules/closures/closures.service.js
  modules/color/color.model.js
  modules/color/color.resolver.js
  modules/comment/comment.model.js
  modules/comment/comment.resolver.js
  modules/comment/comment.service.js
  modules/common/Address.js
  modules/common/ImageSet.js
  modules/constructor/constructor-basic/constructor-basic.model.js
  modules/constructor/constructor-basic/constructor-basic.resolves.js
  modules/constructor/constructor-bottom/constructor-bottom.model.js
  modules/constructor/constructor-bottom/constructor-bottom.resolver.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.model.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.resolves.js
  modules/contact/contact.model.js
  modules/contact/contact.permission.js
  modules/contact/contact.resolver.js
  modules/contact/contact.service.js
  modules/contact/contact.utils.js
  modules/currency/__mocks__/currency.model.js
  modules/currency/__mocks__/currency.utils.js
  modules/currency/currency.model.js
  modules/currency/currency.resolver.js
  modules/currency/currency.service.js
  modules/currency/currency.utils.js
  modules/delivery/nova-poshta/nova-poshta.service.js
  modules/delivery/ukr-poshta/ukr-poshta.service.js
  modules/email-chat/email-chat.model.js
  modules/email-chat/email-chat.resolver.js
  modules/email-chat/email-chat.service.js
  package-lock.json
Labels: BackEnd, Fixes needed

#548 add validation middleware for register user
  consts/input-fields.js
  consts/regexp.js
  consts/status-codes.js
  modules/order/order.graphql.js
  modules/order/order.model.js
  modules/user/user.model.js
  modules/user/user.permissions.js
  modules/user/user.service.js
  package-lock.json
  package.json
  utils/rules.js
  validators/user.validator.js
Labels: BackEnd, Task

#557 add host and port to transporter
  package.json
  utils/email-service.js
Labels: BackEnd

#556 Removed magic strings and numbers from our modules #536
  consts/brand-names.js
  consts/db-collections-names.js
  consts/email-subjects.js
  consts/image-sizes.js
  consts/index.js
  consts/languages.js
  consts/material-purposes.js
  consts/order-statuses.js
  consts/payment-statuses.js
  consts/payment-types.js
  consts/product-features.js
  modules/header/header.model.js
  modules/header/header.resolver.js
  modules/homepage-images/home-page-images.model.js
  modules/homepage-images/home-page-images.resolver.js
  modules/homepage-slider/homepage-slider.model.js
  modules/homepage-slider/homepage-slider.resolves.js
  modules/material/material.model.js
  modules/material/material.resolver.js
  modules/material/material.service.js
  modules/model/model.model.js
  modules/model/model.resolver.js
  modules/news/news.model.js
  modules/news/news.resolver.js
  modules/order/order.model.js
  modules/order/order.resolver.js
  modules/pattern/pattern.model.js
  modules/pattern/pattern.resolver.js
  modules/product/product.model.js
  modules/product/product.resolver.js
  modules/product/product.service.js
  modules/size/size.model.js
  modules/size/size.resolver.js
  modules/upload/upload.service.js
  modules/upload/upload.utils.js
  modules/user/user.model.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  package-lock.json
  utils/product-service.js
Labels: BackEnd, Fixes needed

#574 Implement cart on server
  consts/cart-total-sum-method.js
  consts/currency.js
  consts/db-collections-names.js
  consts/input-fields.js
  error-messages/cart.messages.js
  error-messages/constructor-basic-messages.js
  error-messages/constructor-front-pocket-messages.js
  helpers/calculateCartItemPrice.js
  helpers/calculateCartTotalSum.js
  helpers/cron-job/index.js
  helpers/cron-job/remember-about-unfinished-cart-operations.js
  modules/cart/cart.model.js
  modules/cart/cart.permissions.js
  modules/cart/cart.resolver.js
  modules/cart/cart.service.js
  modules/email/email.service.js
  modules/size/size.service.js
  modules/user/user.graphql.js
  modules/user/user.model.js
  package-lock.json
  package.json
  permissions.js
  resolvers.js
  server.js
  tests/user/user.helper.js
  typeDefs.js
  utils/cart.js
  utils/getDaysInMilliseconds.js
  utils/rules.js
  validators/cart.validator.js
Labels: BackEnd, DB, Task

#570 added validation for category
  consts/input-fields.js
  modules/category/category.model.js
  modules/category/category.permission.js
  validators/category.validator.js
Labels: BackEnd, DB

#573 Refactor/507
  modules/comment/comment.permissions.js
  modules/user/user.service.js
  server.js
  utils/create-token.js
  utils/create-tokens.js
  utils/token.js
Labels: BackEnd, refactoring

#571 added validation for order
  consts/input-fields.js
  consts/order-details.js
  modules/order/order.model.js
  modules/order/order.permissions.js
  permissions.js
  tests/order/order.helpers.js
  tests/order/order.variables.js
  validators/order.validator.js
Labels: BackEnd, DB

#551 Created function too compare products
  consts/default-images.js
  error-messages/products.messages.js
  modules/product/product.resolver.js
  modules/product/product.service.js
  package.json
  tests/product/product.mutation.test.js
  tests/product/product.query.test.js
Labels: BackEnd

#567 added query getRecentComments
  error-messages/comment.messages.js
  modules/comment/comment.permissions.js
  modules/comment/comment.resolver.js
  modules/comment/comment.service.js
  typeDefs.js
Labels: BackEnd

#559 Implement payment service
  consts/fondy-responce-status.js
  consts/hash-features.js
  consts/order-payment-status.js
  consts/payments.js
  dump/horondi/agendaJobs.bson
  dump/horondi/agendaJobs.metadata.json
  dump/horondi/backgrounds.bson
  dump/horondi/backgrounds.metadata.json
  dump/horondi/businesstexts.bson
  dump/horondi/businesstexts.metadata.json
  dump/horondi/categories.bson
  dump/horondi/categories.metadata.json
  dump/horondi/closures.bson
  dump/horondi/closures.metadata.json
  dump/horondi/contacts.bson
  dump/horondi/contacts.metadata.json
  dump/horondi/currencies.bson
  dump/horondi/currencies.metadata.json
  dump/horondi/emailchats.bson
  dump/horondi/emailchats.metadata.json
  dump/horondi/headers.bson
  dump/horondi/headers.metadata.json
  dump/horondi/homepageslides.bson
  dump/horondi/homepageslides.metadata.json
  dump/horondi/looksimages.bson
  dump/horondi/looksimages.metadata.json
  dump/horondi/materials.bson
  dump/horondi/materials.metadata.json
  dump/horondi/models.bson
  dump/horondi/models.metadata.json
  dump/horondi/news.bson
  dump/horondi/news.metadata.json
  dump/horondi/patterns.bson
  dump/horondi/patterns.metadata.json
  dump/horondi/products.bson
  dump/horondi/products.metadata.json
  dump/horondi/sizes.bson
  dump/horondi/sizes.metadata.json
  dump/horondi/users.bson
  dump/horondi/users.metadata.json
  error-messages/orders.messages.js
  error-messages/payment.messages.js
  helpers/payment-controller.js
  modules/order/order.graphql.js
  modules/order/order.model.js
  modules/order/order.resolver.js
  modules/order/order.service.js
  modules/payment/payment.graphql.js
  modules/payment/payment.resolver.js
  modules/payment/payment.service.js
  package-lock.json
  package.json
  server.js
  typeDefs.js
  utils/order.utils.js
  utils/payment.utils.js
Labels: BackEnd, Task

#588 Add migration for set users carts
  helpers/cron-job/remember-about-unfinished-cart-operations.js
  migrate-mongo-config.js
  migrations/20210327122037-set_users_carts.js
  modules/cart/cart.resolver.js
  modules/cart/cart.service.js
  modules/user/user.service.js
  package-lock.json
  utils/rules.js
Labels: BackEnd, DB

#590 Implement block,unlock users
  consts/migrations.js
  consts/user-block-period.js
  email-templates/block-user.pug
  error-messages/user.messages.js
  helpers/cron-job/index.js
  helpers/cron-job/remember-about-unfinished-cart-operations.js
  helpers/cron-job/unlock-users.js
  migrate-mongo-config.js
  migrations/20210328143823-modify_user_banned_field.js
  modules/user/user.graphql.js
  modules/user/user.model.js
  modules/user/user.permissions.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  tests/helpers/users.js
  tests/user/user.helper.js
  tests/user/user.mutation.test.js
  tests/user/user.query.test.js
  tests/user/user.variables.js
  typeDefs.js
  utils/rules.js
Labels: BackEnd, DB

#592 Added fields 'region' and 'district' to order schemas
  consts/regexp.js
  models/Delivery.js
  modules/order/order.graphql.js
  tests/user/user.mutation.test.js
  tests/user/user.variables.js
  validators/order.validator.js
Labels: BackEnd, DB
