Repository ita-social-projects/horondi_client_be, pull requests merged in 2021-06, with the labels that each got.

#673 Changes in typeDefs
  typeDefs.js
Labels: BackEnd, bug

#666 add ID to DB/orders & serch order by ID
  modules/order/order.graphql.js
  modules/order/order.model.js
  modules/order/order.permissions.js
  modules/order/order.resolver.js
  modules/order/order.service.js
  tests/order/order.query.test.js
Labels: BackEnd, refactoring

#654 Added Joi validation to homepage-slider module
  consts/input-fields.js
  helpers/tokenChecker.js
  modules/homepage-slider/homepage-slider.model.js
  modules/homepage-slider/homepage-slider.permission.js
  modules/news/news.service.js
  modules/user/user.service.js
  validators/homepage-slider.validator.js
Labels: BackEnd

#676 Changes of mutation in updateOrder
  modules/order/order.resolver.js
  modules/order/order.service.js
Labels: BackEnd, refactoring

#680 Add new method getCountOrdersUser
  modules/order/order.resolver.js
  modules/order/order.service.js
  modules/user/user.permissions.js
  modules/user/user.resolver.js
  modules/user/user.service.js
  typeDefs.js
Labels: BackEnd

#683 Fixed data fetching and filters to QnA page Bug fix/401
  consts/email-actions.js
  email-templates/answer-email-question.pug
  email-templates/css/main.css
  email-templates/index.js
  modules/email-chat/email-chat.service.js
  modules/email/email.service.js
  typeDefs.js
Labels: BackEnd
