Repository ita-social-projects/horondi_client_be, pull requests merged in 2022-08, with the labels that each got.

#1248 Tests/709/tests for currency service
  modules/currency/currency.service.js
  tests/currency/currency.helper.js
  tests/currency/currency.mutation.test.js
  tests/currency/currency.query.test.js
  tests/currency/currency.variables.js
Labels: test, BackEnd

#1247 Wrong order payment status
  modules/payment/payment.service.js
Labels: BackEnd

#1254 delete redundant getCertificateByName and fixed
  modules/certificate/certificate.graphql.js
  modules/certificate/certificate.resolver.js
  modules/certificate/certificate.service.js
  modules/certificate/certificates.permission.js
  tests/certificate/certificate.helper.js
  tests/certificate/certificate.mutation.test.js
  tests/certificate/certificate.permission.test.js
  tests/certificate/certificate.query.test.js
Labels: BackEnd

#1258 Fixed appearance of non-own certificates
  modules/certificate/certificate.graphql.js
  modules/certificate/certificate.resolver.js
  modules/certificate/certificate.service.js
  modules/certificate/certificates.permission.js
  tests/certificate/certificate.helper.js
  tests/certificate/certificate.permission.test.js
Labels: bug, BackEnd

#1260 Certificate is added to profile without paying for it
  modules/certificate/certificate.resolver.js
  modules/certificate/certificate.service.js
  tests/certificate/certificate.helper.js
  tests/certificate/certificate.permission.test.js
  tests/certificate/certificate.query.test.js
Labels: BackEnd

#1261 Start date of certificate doesn`t match date of purchase
  modules/certificate/certificate.service.js
  tests/utils/modify-date.test.js
  utils/modify-date.js
Labels: bug, BackEnd

#1266 Feature/1265/Certificates sorting
  helpers/filter-helper.js
  modules/certificate/certificate.service.js
  tests/certificate/certificate.permission.test.js
  tests/filter-helper/filter-helper.helper.js
Labels: BackEnd, feature
