Repository ita-social-projects/horondi_client_be, pull requests merged in 2022-03, with the labels that each got.

#1143 fixing incorrect view of email
  email-templates/css/adaptive.css
  email-templates/css/main.css
  email-templates/template-en.pug
Labels: bug, BackEnd, email

#1142 feature/1060/certificate reminder via email
  email-templates/certificate-reminder-en.pug
  email-templates/certificate-reminder-ua.pug
  helpers/cron-job/certificates-expire-check.js
  modules/certificate/certificate.service.js
Labels: BackEnd, feature, email

#1141 Feature/1132/add configs user
  modules/user/user.graphql.js
  modules/user/user.model.js
  typeDefs.js
Labels: BackEnd

#1158 eslint refactor
  .eslintrc.json
  .prettierrc
  modules/model/model.resolver.js
  modules/model/model.service.js
  modules/news/news.service.js
  modules/order/order.service.js
  modules/pattern/pattern.model.js
  modules/pattern/pattern.service.js
  package-lock.json
  tests/payment/payment.helper.js
  tests/payment/payment.query.test.js
  tests/pocket/pocket.helper.js
  tests/position/position.helpers.js
  tests/product/product.helper.js
Labels: refactoring

#1151 Bugfix/1150/delete product refactoring
  modules/product/product.permissions.js
  modules/product/product.resolver.js
  modules/product/product.service.js
  resolvers.js
  tests/comment/comment.mutations.test.js
  tests/comment/comment.query.test.js
  tests/order/order.mutation.test.js
  tests/order/order.query.test.js
  tests/payment/payment.query.test.js
  tests/product/product.helper.js
  tests/product/product.mutation.test.js
  tests/product/product.query.test.js
  typeDefs.js
Labels: refactoring, BackEnd

#1161 fix eslint errors and warnings
  .eslintrc.json
  client/jwt-client.js
  consts/delivery-services.js
  consts/index.js
  consts/regexp.js
  currency.worker.js
  dotenvValidator.js
  dump-database.js
  logger.js
  migrations/20210215165258-add_name_field_for_sizes.js
  migrations/20210418172905-add-fields-to-closures.js
  migrations/20210418181215-update-fields-in-patterns.js
  migrations/20210418184317-update-fields-in-constructorBasic.js
  migrations/20210418203406-update-fields-in-constructorBottom.js
  migrations/20210418204054-update-fields-in-constructorFrontPockets.js
  migrations/20210418204846-update-fields-in-models.js
  migrations/20210526200334-update-fields-in-remaining-constructorBasics.js
  migrations/20210617215314-update-sizes-models-relations.js
  migrations/20211017073947-refactor_contacts.js
  tests/back/back.helper.js
  tests/basics/basics.helper.js
  tests/bottom/bottom.helper.js
  tests/business-text/business-text.query.test.js
  tests/business-text/bussiness-text.helper.js
Labels: eslint

#1154 Feature/1152/refactor fondy
  .eslintrc.json
  error-messages/certificate.messages.js
  error-messages/orders.messages.js
  modules/certificate/certificate.graphql.js
  modules/certificate/certificate.resolver.js
  modules/certificate/certificate.service.js
  modules/order/order.resolver.js
  modules/order/order.service.js
  modules/payment/payment.resolver.js
  modules/payment/payment.service.js
  pubsub.js
  resolvers.js
  server.js
  tests/certificate/certificate.helper.js
  tests/certificate/certificate.query.test.js
  tests/order/order.helpers.js
  tests/order/order.query.test.js
  tests/payment/payment.helper.js
  tests/payment/payment.query.test.js
  typeDefs.js
Labels: BackEnd, feature
