Repository ita-social-projects/horondi_client_be, pull requests merged in 2022-01, with the labels that each got.

#995 Refactor/985/group history
  consts/history-actions.js
  consts/history-events.js
  helpers/cron-job/unlock-users.js
  modules/back/back.service.js
  modules/basics/basics.service.js
  modules/bottom/bottom.service.js
  modules/category/category.service.js
  modules/closures/closures.service.js
  modules/color/color.service.js
  modules/constructor/constructor.services.js
  modules/constructor_new/constructor.service.js
  modules/history/history.graphql.js
  modules/history/history.model.js
  modules/history/history.service.js
  modules/material/material.service.js
  modules/model/model.service.js
  modules/news/news.service.js
  modules/pattern/pattern.service.js
  modules/pocket/pocket.service.js
  modules/position/position.service.js
  modules/product/product.service.js
  modules/restriction/restriction.service.js
  modules/size/size.service.js
  modules/strap/strap.service.js
  modules/user/user.service.js
  tests/history/history.helper.js
  tests/history/history.query.test.js
  tests/history/history.variables.js
  utils/history.js
Labels: BackEnd

#1017 Added district field to address model
  error-messages/address.messages.js
  modules/common/Address.js
  tests/user/user.helper.js
  typeDefs.js
  validators/user.validator.js
Labels: BackEnd

#1020 add promo-code to back
  consts/db-collections-names.js
  modules/promo-code/promo-code.graphql.js
  modules/promo-code/promo-code.model.js
  modules/promo-code/promo-code.permissions.js
  modules/promo-code/promo-code.resolver.js
  modules/promo-code/promo-code.service.js
  permissions.js
  resolvers.js
  tests/promo-code/promo-code.helper.js
  tests/promo-code/promo-code.mutation.test.js
  tests/promo-code/promo-code.query.test.js
  tests/promo-code/promo-code.variables.js
  typeDefs.js
Labels: BackEnd, feature

#1050 refactor/1041/remove cart
  consts/cart-total-sum-method.js
  consts/db-collections-names.js
  consts/email-actions.js
  email-templates/incomplete-operations-en.pug
  email-templates/incomplete-operations-ua.pug
  email-templates/index.js
  error-messages/cart.messages.js
  helpers/calculateCartItemPrice.js
  helpers/calculateCartTotalSum.js
  helpers/cron-job/index.js
  helpers/cron-job/remember-about-unfinished-cart-operations.js
  migrations/20210327122037-set_users_carts.js
  modules/cart/cart.model.js
  modules/cart/cart.permissions.js
  modules/cart/cart.resolver.js
  modules/cart/cart.service.js
  modules/product/product.graphql.js
  modules/product/product.service.js
  modules/user/user.graphql.js
  modules/user/user.model.js
  permissions.js
  resolvers.js
  tests/cart/cart.helper.js
  tests/cart/cart.mutation.test.js
  tests/cart/cart.query.test.js
  tests/cart/cart.variables.js
  tests/cart/changeCartItemSizeHandler.test.js
  tests/product/product.helper.js
  tests/product/product.query.test.js
  typeDefs.js
  utils/cart.js
  utils/changeCartItemSizeHandler.js
  utils/rules.js
  validators/cart.validator.js
Labels: refactoring, BackEnd

#1059 create category field in promocode
  modules/promo-code/promo-code.graphql.js
  modules/promo-code/promo-code.model.js
  modules/promo-code/promo-code.service.js
Labels: BackEnd

#1072 Feature/1071/get-PromoCode-By-Code
  error-messages/promocode.messages.js
  modules/promo-code/promo-code.permissions.js
  modules/promo-code/promo-code.resolver.js
  modules/promo-code/promo-code.service.js
  permissions.js
  resolvers.js
  tests/promo-code/promo-code.helper.js
  tests/promo-code/promo-code.query.test.js
  typeDefs.js
Labels: BackEnd

#1078 Feature/1053/update promocode
  consts/promocode-fields.js
  error-messages/promocode-messages.js
  modules/promo-code/promo-code.graphql.js
  modules/promo-code/promo-code.model.js
  modules/promo-code/promo-code.permissions.js
  modules/promo-code/promo-code.resolver.js
  modules/promo-code/promo-code.service.js
  tests/promo-code/promo-code.helper.js
  tests/promo-code/promo-code.mutation.test.js
  tests/promo-code/promo-code.variables.js
  typeDefs.js
  validators/promocode-validator.js
Labels: BackEnd, functional

#1091 Fix/1071/handle-error
  modules/promo-code/promo-code.resolver.js
  tests/promo-code/promo-code.helper.js
  tests/promo-code/promo-code.query.test.js
Labels: BackEnd
