Repository ita-social-projects/horondi_client_be, pull requests merged in 2022-12, with the labels that each got.

#1331 Can`t delete the last additional photo in the product
  consts/default-images.js
  modules/product/product.graphql.js
  modules/product/product.service.js
  validators/product.validator.js
Labels: bug

#1336 Change history object saving, add soft delete to history
  modules/model/model.graphql.js
  modules/model/model.helper.js
  modules/model/model.resolver.js
  modules/model/model.service.js
  tests/model/model.helper.js
  tests/model/model.mutation.test.js
  utils/history.js
Labels: BackEnd

#1342 A last order should be first in the order list.
  modules/order/order.service.js
Labels: bug, BackEnd

#1346 add error when admin create promo-code with same name
  error-messages/promocode-messages.js
  modules/promo-code/promo-code.service.js
Labels: bug, BackEnd

#1348 bugFix/2299/constructor-price-calculation
  models/OrderItem.js
  modules/order/order.graphql.js
  modules/payment/payment.service.js
  modules/product/product.service.js
  resolvers.js
  tests/order/order.variables.js
  utils/final-price-calculation.js
Labels: bug, BackEnd

#1353 now email successfuly sending after payment
  modules/order/order.service.js
  modules/payment/payment.graphql.js
  modules/payment/payment.service.js
  tests/payment/payment.query.test.js
  utils/payment.utils.js
Labels: bug, BackEnd

#1358 Changed button title in pug
  email-templates/confirm-email-ua.pug
Labels: BackEnd
