Repository ita-social-projects/horondi_client_be, pull requests merged in 2022-11, with the labels that each got.

#1303 add date of using in certificates
  modules/certificate/certificate.graphql.js
  modules/certificate/certificate.model.js
  modules/certificate/certificate.service.js
  modules/payment/payment.service.js
  tests/certificate/certificate.helper.js
  tests/payment/payment.query.test.js
Labels: bug, BackEnd

#1306 bug/1291/currency-worker
  tests/config.test.app.js
Labels: bug, BackEnd

#1308 Bugfix/1307/remove upload from add product from constructor
  modules/product/product.resolver.js
  typeDefs.js
Labels: BackEnd

#1310 [Orders] Fix an error when you click on edit icon
  modules/size/size.service.js
  resolvers.js
Labels: bug, BackEnd

#1316 remove all spaces and brackets while upload image
  consts/regexp.js
  modules/upload/upload.service.js
Labels: bug, BackEnd

#1304 payment status changing
  modules/order/order.service.js
  tests/order/order.query.test.js
  tests/order/order.variables.js
Labels: bug, Admin

#1318 certificate status change according to order status
  consts/order-payment-status.js
  modules/order/order.service.js
Labels: BackEnd

#1319 Should receive reject from Fondy if order was canceled
  consts/order-payment-status.js
  modules/order/order.service.js
  modules/payment/payment.service.js
  modules/product/product.service.js
  tests/payment/payment.query.test.js
Labels: BackEnd

#1322 changed regEx
  consts/regexp.js
Labels: bug, BackEnd

#1325 change certificate status to in progress when adding it to new order
  modules/order/order.service.js
  tests/order/order.mutation.test.js
Labels: BackEnd

#1327 Bug/1326/fix promocode validation
  validators/promocode-validator.js
Labels: bug, BackEnd
