Repository ita-social-projects/horondi_client_be, pull requests merged in 2022-04, with the labels that each got.

#1172 Bugfix/1171/user question is not sent
  consts/regexp.js
Labels: bug, BackEnd

#1170 fixed bug with editing tapestry
  modules/pattern/pattern.service.js
  utils/final-price-calculation.js
Labels: bug, BackEnd

#1177 Bugfix/1176/add first name last name to certificates service
  modules/certificate/certificate.service.js
Labels: bug, BackEnd, Admin

#1145 feature/1125 added filtering to getAllCertificates + fixed massgenerating
  helpers/cron-job/certificates-expire-check.js
  modules/certificate/certificate.graphql.js
  modules/certificate/certificate.resolver.js
  modules/certificate/certificate.service.js
  resolvers.js
  tests/certificate/certificate.helper.js
  tests/certificate/certificate.permission.test.js
  tests/certificate/certificate.query.test.js
  tests/utils/modify-date.test.js
  utils/modify-date.js
Labels: BackEnd

#1180 Feature/1186/pagination in admin for promocode be
  modules/promo-code/promo-code.service.js
Labels: bug, BackEnd

#1181 Martynyk/order-price-refactor
  consts/currency.js
  consts/db-collections-names.js
  models/Closure.js
  models/CurrencySet.js
  models/Delivery.js
  models/OrderItem.js
  modules/constructor/constructor-basic/constructor-basic.graphgl.js
  modules/constructor/constructor-basic/constructor-basic.model.js
  modules/constructor/constructor-bottom/constructor-bottom.graphql.js
  modules/constructor/constructor-bottom/constructor-bottom.model.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.graphgl.js
  modules/constructor/constructor-front-pocket/constructor-front-pocket.model.js
  modules/constructor/constructor.services.js
  modules/material/material.graphql.js
  modules/order/order.graphql.js
  modules/order/order.model.js
  typeDefs.js
  utils/order.utils.js
  validators/order.validator.js
Labels: refactoring, BackEnd

#1183 Add_field_admin_to_certificate.graphql
  modules/certificate/certificate.graphql.js
Labels: bug, BackEnd

#1179 Fix "Created At" bug
  modules/history/history.model.js
  tests/history/history.variables.js
Labels: bug, BackEnd

#1185 add fixed exchange rate property to order model
  modules/order/order.graphql.js
  modules/order/order.model.js
  modules/order/order.service.js
Labels: refactoring, BackEnd

#1186 Change update certificate method
  modules/certificate/certificate.service.js
Labels: BackEnd
