Repository ita-social-projects/horondi_client_be, pull requests merged in 2022-07, with the labels that each got.

#1224 Displayed price without discount within promo code was used
  modules/order/order.graphql.js
  modules/order/order.model.js
  modules/order/order.service.js
  tests/utils/order/order.utils.test.js
  tests/utils/order/order.utils.variables.js
  utils/order.utils.js
  validators/order.validator.js
Labels: test, BackEnd

#1226 Added image upload service to materials page
  modules/materials-page/materials-page.graphql.js
  modules/materials-page/materials-page.model.js
  modules/materials-page/materials-page.resolver.js
  modules/materials-page/materials-page.service.js
  tests/materials-page/materials-page.helper.js
  tests/materials-page/materials-page.mutation.test.js
  tests/materials-page/materials-page.query.test.js
  tests/materials-page/materials-page.variables.js
  typeDefs.js
Labels: BackEnd, feature

#1236 fixed SonarCloud code smells on back end
  consts/regexp.js
  helpers/cron-job/clear-logs-in-mongodb.js
  modules/business-text/business-text.resolver.js
  modules/business-text/business-text.service.js
  modules/category/category.resolver.js
  modules/color/color.resolver.js
  modules/comment/comment.resolver.js
  modules/contact/contact.resolver.js
  modules/currency/currency.resolver.js
  modules/delivery/nova-poshta/nova-poshta.resolver.js
  modules/delivery/ukr-poshta/ukr-poshta.resolver.js
  modules/email-chat/email-chat.resolver.js
  modules/homepage-images/home-page-images.resolver.js
  modules/homepage-slider/homepage-slider.resolves.js
  modules/material/material.resolver.js
  modules/news/news.resolver.js
  modules/order/order.resolver.js
  modules/product/product.service.js
  modules/size/size.resolver.js
  modules/upload/upload.resolver.js
  modules/user/user.model.js
  modules/user/user.resolver.js
  modules/wishlist/wishlist.resolver.js
  utils/rules.js
Labels: BackEnd

#1235 Improvement/1233/embed size entity into model entity
  consts/history-events.js
  consts/migrations.js
  email-templates/payment-order-en.pug
  migrations/20220716152228-move-sizes-to-models.js
  migrations/20220716220956-modify-sizes-for-products-and-orders.js
  migrations/20220718221331-add-soft-deletion-fields-to-models.js
  models/OrderItem.js
  modules/model/model.graphql.js
  modules/model/model.helper.js
  modules/model/model.model.js
  modules/model/model.resolver.js
  modules/model/model.service.js
  modules/payment/payment.service.js
  modules/product/product.model.js
  modules/product/product.service.js
  modules/size/size.graphql.js
  modules/size/size.model.js
  modules/size/size.permissions.js
  modules/size/size.resolver.js
  modules/size/size.service.js
  permissions.js
  resolvers.js
  tests/back/back.mutation.test.js
  tests/back/back.query.test.js
  tests/closure/closure.mutation.test.js
  tests/closure/closure.query.test.js
  tests/comment/comment.mutations.test.js
  tests/comment/comment.query.test.js
  tests/constructor-basic/constructor-basic.mutation.test.js
  tests/constructor-basic/constructor-basic.query.test.js
  tests/constructor-bottom/constructor-bottom.query.test.js
  tests/constructor-front/constructor.mutation.test.js
  tests/history/history.query.test.js
  tests/history/history.variables.js
  tests/model/model.helper.js
  tests/model/model.mutation.test.js
  tests/model/model.variables.js
  tests/order/order.mutation.test.js
  tests/order/order.query.test.js
  tests/pattern/pattern.query.test.js
  tests/payment/payment.query.test.js
  tests/product/product.mutation.test.js
  tests/product/product.query.test.js
  tests/size/size.helper.js
  tests/size/size.mutations.test.js
  tests/size/size.queries.test.js
  tests/size/size.variables.js
  typeDefs.js
  utils/createTranslations.js
  utils/final-price-calculation.js
  validators/model.validator.js
  validators/size.validator.js
Labels: data base, BackEnd

#1240 add possibility to get certificate by name
  modules/certificate/certificate.graphql.js
  modules/certificate/certificate.resolver.js
  modules/certificate/certificate.service.js
  modules/certificate/certificates.permission.js
  tests/certificate/certificate.helper.js
  tests/certificate/certificate.mutation.test.js
  tests/certificate/certificate.permission.test.js
  tests/certificate/certificate.query.test.js
Labels: BackEnd

#1238 Add an image updater in updateMaterialsBlock
  modules/materials-page/materials-page.resolver.js
  modules/materials-page/materials-page.service.js
  tests/materials-page/materials-page.helper.js
  tests/materials-page/materials-page.mutation.test.js
  typeDefs.js
Labels: BackEnd, feature

#1242 Added history records for materials pages
  consts/history-events.js
  consts/history-obj-keys.js
  modules/materials-page/materials-page.resolver.js
  modules/materials-page/materials-page.service.js
Labels: BackEnd, feature

#1245 Bugfix/1225/upload service outdated
  package-lock.json
  package.json
  server.js
Labels: bug, BackEnd
