Repository ita-social-projects/horondi_client_be, pull requests merged in 2022-09, with the labels that each got.

#1271 price display with discount when you add certificate
  modules/order/order.graphql.js
  modules/order/order.model.js
  modules/order/order.service.js
  tests/utils/order/order.utils.test.js
  tests/utils/order/order.utils.variables.js
  utils/order.utils.js
  validators/order.validator.js
Labels: BackEnd, feature

#1273 Added link to redirect after order payment
  modules/payment/payment.service.js
  resolvers.js
  typeDefs.js
Labels: BackEnd

#1268 User can login without confirm email
  error-messages/user.messages.js
  modules/user/user.service.js
  tests/certificate/certificate.permission.test.js
  tests/user/user.mutation.test.js
  tests/user/user.query.test.js
Labels: bug, BackEnd

#1278 Created posibility to gift certificate and send emails
  consts/email-actions.js
  email-templates/css/adaptive.css
  email-templates/css/main.css
  email-templates/img/email-templates.jpg
  email-templates/img/headerBackground.png
  email-templates/index.js
  email-templates/receive-gift-certificate-en.pug
  email-templates/receive-gift-certificate-ua.pug
  email-templates/send-gift-certificate-en.pug
  email-templates/send-gift-certificate-ua.pug
  modules/certificate/certificate.graphql.js
  modules/certificate/certificate.resolver.js
  modules/certificate/certificate.service.js
  tests/certificate/certificate.helper.js
  tests/certificate/certificate.mutation.test.js
  tests/certificate/certificate.variables.js
  tests/color/color.mutations.test.js
  tests/color/color.query.test.js
  tests/user/user.query.test.js
Labels: BackEnd, feature

#1280 Feature/1279/certificate status change
  consts/certificate-update-status.js
  error-messages/certificate.messages.js
  helpers/cron-job/certificates-expire-check.js
  modules/certificate/certificate.graphql.js
  modules/certificate/certificate.model.js
  modules/certificate/certificate.resolver.js
  modules/certificate/certificate.service.js
  modules/certificate/certificates.permission.js
  modules/order/order.service.js
  modules/payment/payment.service.js
  tests/certificate/certificate.helper.js
  tests/certificate/certificate.mutation.test.js
  tests/certificate/certificate.permission.test.js
  tests/certificate/certificate.query.test.js
  tests/order/order.helpers.js
  tests/order/order.mutation.test.js
  tests/order/order.query.test.js
  tests/order/order.variables.js
  tests/payment/payment.query.test.js
  tests/payment/payment.variables.js
Labels: BackEnd, feature

#1282 Certificate thanks page is not displayed after payment
  consts/payments.js
  email-templates/certificate-user-purchased-email-en.pug
  email-templates/certificate-user-purchased-email-ua.pug
  error-messages/certificate.messages.js
  modules/certificate/certificate.model.js
  modules/certificate/certificate.service.js
  modules/payment/payment.graphql.js
  modules/payment/payment.service.js
  server.js
  tests/certificate/certificate.permission.test.js
  tests/payment/payment.query.test.js
Labels: BackEnd

#1283 Send an email when the certificate expires soon
  email-templates/certificate-reminder-en.pug
  email-templates/certificate-reminder-ua.pug
  email-templates/certificate-user-purchased-email-en.pug
  email-templates/certificate-user-purchased-email-ua.pug
  email-templates/confirm-admin-email-en.pug
  email-templates/confirm-admin-email-ua.pug
  email-templates/confirm-email-en.pug
  email-templates/confirm-email-ua.pug
  email-templates/css/adaptive.css
  email-templates/css/main.css
  email-templates/index.js
  email-templates/receive-gift-certificate-en.pug
  email-templates/receive-gift-certificate-ua.pug
  email-templates/recover-password-en.pug
  email-templates/recover-password-ua.pug
  email-templates/send-gift-certificate-en.pug
  email-templates/send-gift-certificate-ua.pug
  email-templates/successful-order-en.pug
  email-templates/successful-order-ua.pug
  email-templates/successfully-registered-en.pug
  email-templates/successfully-registered-ua.pug
  helpers/cron-job/certificates-expire-check.js
  modules/certificate/certificate.service.js
  modules/payment/payment.service.js
  server.js
  tests/payment/payment.query.test.js
Labels: BackEnd
