Repository ita-social-projects/horondi_client_be, pull requests merged in 2022-10, with the labels that each got.

#1284 The certificate must be attached to the email
  modules/certificate/certificate.service.js
  tests/certificate/certificate.permission.test.js
Labels: BackEnd

#1288 Added password recovery error
  modules/user/user.service.js
  tests/user/user.mutation.test.js
Labels: BackEnd

#1286 Notify the user on the certificate expires
  helpers/cron-job/certificates-expire-check.js
  modules/user/user.graphql.js
  modules/user/user.model.js
  modules/user/user.service.js
  tests/helpers/cron/certificates-expire-check.test.js
Labels: BackEnd

#1290 Users that are not admins can login
  modules/user/user.service.js
  tests/business-text/business-text.mutation.test.js
Labels: BackEnd

#1296 refactor successful payment pug
  email-templates/css/adaptive.css
  email-templates/css/main.css
  email-templates/successful-order-en.pug
  email-templates/successful-order-ua.pug
  modules/order/order.model.js
  modules/payment/payment.service.js
  tests/payment/payment.variables.js
Labels: bug, BackEnd

#1299 refactored pockets
  modules/constructor_new/constructor.graphql.js
  modules/constructor_new/constructor.model.js
  resolvers.js
  tests/constructor-new/constructor.variables.js
  validators/constructor-items-inputs.validator.js
Labels: BackEnd, constructor

#1301 Get sizes that were ordered
  modules/size/size.service.js
  resolvers.js
Labels: BackEnd
