Repository ita-social-projects/horondi_client_be, pull requests merged in 2022-02, with the labels that each got.

#1061 Cron jobs for certificate
  consts/cron-period.js
  consts/email-actions.js
  email-templates/certificate-reminder-en.pug
  email-templates/certificate-reminder-ua.pug
  email-templates/index.js
  helpers/cron-job/certificates-expire-check.js
  helpers/cron-job/index.js
  helpers/cron-job/unlock-users.js
  modules/certificate/certificate.model.js
  modules/certificate/certificate.service.js
  tests/helpers/cron/certificates-expire-check.test.js
  tests/utils/modify-date.test.js
  utils/modify-date.js
Labels: BackEnd

#1086 Feature/1077/implement back end for about material page
  consts/db-collections-names.js
  modules/materials-page/materials-page.graphql.js
  modules/materials-page/materials-page.model.js
  modules/materials-page/materials-page.permissions.js
  modules/materials-page/materials-page.resolver.js
  modules/materials-page/materials-page.service.js
  permissions.js
  resolvers.js
  tests/materials-page/materials-page.helper.js
  tests/materials-page/materials-page.mutation.test.js
  tests/materials-page/materials-page.query.test.js
  tests/materials-page/materials-page.variables.js
  typeDefs.js
Labels: BackEnd, feature

#1093 Updated eslint
  .eslintignore
  .eslintrc
  .eslintrc.json
  .prettierrc
  package.json
Labels: BackEnd, eslint

#1097 Feature/1094/constructor product save
  modules/product/product.graphql.js
  modules/product/product.permissions.js
  modules/product/product.resolver.js
  modules/product/product.service.js
  typeDefs.js
  utils/final-price-calculation.js
  validators/product.validator.js
Labels: BackEnd

#1098 Certificates email template
  consts/email-actions.js
  email-templates/certificate-user-purchased-email-en.pug
  email-templates/certificate-user-purchased-email-ua.pug
  email-templates/index.js
Labels: BackEnd, email

#1105 add new params to dockerFile
  Dockerfile
Labels: BackEnd

#1120 Fixed product from constructor save
  modules/product/product.graphql.js
  modules/product/product.model.js
  modules/product/product.service.js
  utils/final-price-calculation.js
  validators/product.validator.js
Labels: bug, BackEnd

#1118 Fixed wishlist error
  modules/user/user.service.js
Labels: bug, BackEnd

#1123 Feature/1122/Created certificate payment module
  modules/certificate/certificate.graphql.js
  modules/certificate/certificate.resolver.js
  modules/certificate/certificate.service.js
  modules/payment/payment.graphql.js
  modules/payment/payment.resolver.js
  modules/payment/payment.service.js
  server.js
  tests/certificate/certificate.helper.js
  tests/certificate/certificate.permission.test.js
  tests/certificate/certificate.query.test.js
  tests/certificate/certificate.variables.js
  tests/order/order.helpers.js
  tests/payment/payment.helper.js
  tests/payment/payment.query.test.js
  typeDefs.js
Labels: BackEnd, feature

#1126 Feature/1124/check-promoCode-expire
  .env.example
  modules/promo-code/promo-code.service.js
  tests/promo-code/promo-code.variables.js
Labels: BackEnd

#1136 Feature/1109/update prettier
  package.json
Labels: dependencies, BackEnd

#1137 Fix/1131/filter-catalog
  modules/product/product.service.js
Labels: bug, BackEnd
